version: '2'
formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/stretchr/testify)
        - prefix(github.com/inference-gateway/adk/server/mocks)
        - default
        - prefix(github.com/inference-gateway/)
        - prefix(github.com/inference-gateway/adk)
  exclusions:
    generated: lax
