version: '2'
linters:
  enable:
    - importas
  settings:
    importas:
      no-unaliased: true
      alias:
        - pkg: go.opentelemetry.io/otel
          alias: otelapi
        - pkg: go.opentelemetry.io/otel/sdk/metric
          alias: sdkmetric
        - pkg: go.opentelemetry.io/otel/sdk/trace
          alias: sdktrace
        - pkg: github.com/cloudevents/sdk-go/v2
          alias: cloudevents
        - pkg: '^[^/]+\.[^/]+/.*?([a-z][a-z0-9]*)(?:-go)?(?:\.v[0-9]+)?(?:/v[0-9][0-9.]*)?$'
          alias: '$1'
  exclusions:
    generated: lax
formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/stretchr/testify)
        - prefix(github.com/inference-gateway/adk/server/mocks)
        - default
        - prefix(github.com/inference-gateway/)
        - prefix(github.com/inference-gateway/adk)
  exclusions:
    generated: lax
