---
version: '3'

tasks:
  default:
    desc: 'Show available tasks'
    cmds:
      - task --list

  a2a:download-schema:
    desc: 'Download the latest A2A schema and convert to YAML'
    cmds:
      - curl -o schema.yaml https://raw.githubusercontent.com/inference-gateway/schemas/refs/heads/main/a2a/a2a-schema.yaml

  a2a:generate-types:
    desc: 'Generate the Golang ADK types from the A2A schema'
    sources:
      - schema.yaml
    generates:
      - types/generated_types.go
    cmds:
      - go run github.com/inference-gateway/tools/cmd/generator@v0.1.2 -generator jsonrpc -package types schema.yaml types/generated_types.go

  tidy:
    desc: 'Tidy all Go modules'
    cmds:
      - find . -name 'go.mod' -execdir go mod tidy \;

  format:
    desc: 'Format all Go files'
    cmds:
      - find . -name '*.go' -exec gofmt -w {} \;
      - find . -name '*.md' -exec prettier -w {} \;

  lint:
    desc: 'Run Go static analysis and linting'
    cmds:
      - golangci-lint run
  
  lint:examples:
    desc: 'Run markdownlint on all examples'
    cmds:
      - markdownlint-cli2 --fix examples/**.md

  test:
    desc: 'Run tests'
    cmds:
      - go test -v -cover ./...

  clean:
    desc: 'Clean up'
    cmds:
      - rm -rf bin

  clean:mocks:
    desc: 'Clean up generated mocks'
    cmds:
      - rm -rf server/mocks/*.go

  generate:mocks:
    desc: 'Generate all mocks using counterfeiter'
    cmds:
      - task: generate:mock:a2a-client
      - task: generate:mock:a2a-server
      - task: generate:mock:a2a-server-builder
      - task: generate:mock:agent-builder
      - task: generate:mock:openai-compatible-agent
      - task: generate:mock:task-handler
      - task: generate:mock:streamable-task-handler
      - task: generate:mock:a2a-protocol-handler
      - task: generate:mock:task-manager
      - task: generate:mock:storage
      - task: generate:mock:response-sender
      - task: generate:mock:oidc-authenticator
      - task: generate:mock:task-result-processor
      - task: generate:mock:telemetry
      - task: generate:mock:opentelemetry
      - task: generate:mock:llm-client
      - task: generate:mock:toolbox
      - task: generate:mock:artifact-storage-provider

  generate:mocks:clean:
    desc: 'Clean and regenerate all mocks'
    cmds:
      - task: clean:mocks
      - task: generate:mocks

  generate:mock:a2a-client:
    desc: 'Generate mock for A2AClient interface'
    sources:
      - client/client.go
    generates:
      - client/mocks/fake_a2a_client.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o client/mocks/fake_a2a_client.go client A2AClient

  generate:mock:a2a-server:
    desc: 'Generate mock for A2AServer interface'
    sources:
      - server/server.go
    generates:
      - server/mocks/fake_a2a_server.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_a2a_server.go server A2AServer

  generate:mock:a2a-server-builder:
    desc: 'Generate mock for A2AServerBuilder interface'
    sources:
      - server/server_builder.go
    generates:
      - server/mocks/fake_a2a_server_builder.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_a2a_server_builder.go server A2AServerBuilder

  generate:mock:task-handler:
    desc: 'Generate mock for TaskHandler interface'
    sources:
      - server/task_handler.go
    generates:
      - server/mocks/fake_task_handler.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_task_handler.go server TaskHandler

  generate:mock:streamable-task-handler:
    desc: 'Generate mock for StreamableTaskHandler interface'
    sources:
      - server/task_handler.go
    generates:
      - server/mocks/fake_streamable_task_handler.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_streamable_task_handler.go server StreamableTaskHandler

  generate:mock:a2a-protocol-handler:
    desc: 'Generate mock for A2AProtocolHandler interface'
    sources:
      - server/task_handler.go
    generates:
      - server/mocks/fake_a2a_protocol_handler.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_a2a_protocol_handler.go server A2AProtocolHandler

  generate:mock:task-manager:
    desc: 'Generate mock for TaskManager interface'
    sources:
      - server/task_manager.go
    generates:
      - server/mocks/fake_task_manager.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_task_manager.go server TaskManager

  generate:mock:storage:
    desc: 'Generate mock for Storage interface'
    sources:
      - server/storage.go
    generates:
      - server/mocks/fake_storage.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_storage.go server Storage

  generate:mock:response-sender:
    desc: 'Generate mock for ResponseSender interface'
    sources:
      - server/response_sender.go
    generates:
      - server/mocks/fake_response_sender.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_response_sender.go server ResponseSender

  generate:mock:tools-provider:
    desc: 'Generate mock for ToolsProvider interface'
    sources:
      - server/agent.go
    generates:
      - server/mocks/fake_tools_provider.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_tools_provider.go server ToolsProvider

  generate:mock:task-result-processor:
    desc: 'Generate mock for TaskResultProcessor interface'
    sources:
      - server/server.go
    generates:
      - server/mocks/fake_task_result_processor.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_task_result_processor.go server TaskResultProcessor

  generate:mock:telemetry:
    desc: 'Generate mock for Telemetry interface'
    sources:
      - server/middlewares/telemetry.go
    generates:
      - server/mocks/fake_telemetry.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_telemetry.go server/middlewares Telemetry

  generate:mock:oidc-authenticator:
    desc: 'Generate mock for OIDCAuthenticator interface'
    sources:
      - server/middlewares/auth.go
    generates:
      - server/mocks/fake_oidc_authenticator.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_oidc_authenticator.go server/middlewares OIDCAuthenticator

  generate:mock:opentelemetry:
    desc: 'Generate mock for OpenTelemetry interface'
    sources:
      - server/otel/opentelemetry.go
    generates:
      - server/mocks/fake_opentelemetry.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_opentelemetry.go server/otel OpenTelemetry

  generate:mock:llm-client:
    desc: 'Generate mock for LLMClient interface'
    sources:
      - server/agent.go
    generates:
      - server/mocks/fake_llm_client.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_llm_client.go server LLMClient

  generate:mock:agent-builder:
    desc: 'Generate mock for AgentBuilder interface'
    sources:
      - server/agent_builder.go
    generates:
      - server/mocks/fake_agent_builder.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_agent_builder.go server AgentBuilder

  generate:mock:openai-compatible-agent:
    desc: 'Generate mock for OpenAICompatibleAgent interface'
    sources:
      - server/agent.go
    generates:
      - server/mocks/fake_openai_compatible_agent.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_openai_compatible_agent.go server OpenAICompatibleAgent

  generate:mock:toolbox:
    desc: 'Generate mock for ToolBox interface'
    sources:
      - server/agent_toolbox.go
    generates:
      - server/mocks/fake_tool_box.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_tool_box.go server ToolBox

  generate:mock:artifact-storage-provider:
    desc: 'Generate mock for ArtifactStorageProvider interface'
    sources:
      - server/artifacts_storage.go
    generates:
      - server/mocks/fake_artifact_storage_provider.go
    cmds:
      - go run github.com/maxbrunsfeld/counterfeiter/v6 -o server/mocks/fake_artifact_storage_provider.go server ArtifactStorageProvider

  precommit:install:
    desc: 'Install the pre-commit hook'
    cmds:
      - cp scripts/pre-commit .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "✅ Pre-commit hook installed successfully!"

  precommit:uninstall:
    desc: 'Uninstall the pre-commit hook'
    cmds:
      - rm -f .git/hooks/pre-commit
      - echo "✅ Pre-commit hook uninstalled successfully!"
