---
services:
  server:
    build:
      context: ../../..
      dockerfile: examples/Dockerfile.server
      args:
        AGENT_NAME: in-memory-queue-example
        AGENT_DESCRIPTION: A2A server demonstrating in-memory queue storage
        AGENT_VERSION: 0.1.0
        LD_FLAGS: "-w -s -X 'main.AgentName=${AGENT_NAME}' -X 'main.AgentDescription=${AGENT_DESCRIPTION}' -X 'main.AgentVersion=${AGENT_VERSION}'"
        EXAMPLE_PATH: examples/queue-storage/in-memory
        COMPONENT: server
    environment:
      ENVIRONMENT: development
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_QUEUE_PROVIDER: memory
      A2A_QUEUE_MAX_SIZE: 100
      A2A_QUEUE_CLEANUP_INTERVAL: 30s
      A2A_TASK_RETENTION_MAX_COMPLETED_TASKS: 50
      A2A_TASK_RETENTION_MAX_FAILED_TASKS: 25
      A2A_TASK_RETENTION_CLEANUP_INTERVAL: 5m
      A2A_CAPABILITIES_STREAMING: true
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - http://localhost:8080/health
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - queue-demo-network

  client:
    build:
      context: ../../..
      dockerfile: examples/Dockerfile.client
      args:
        LD_FLAGS: "-w -s"
        EXAMPLE_PATH: examples/queue-storage/in-memory
        COMPONENT: client
    depends_on:
      server:
        condition: service_healthy
    environment:
      SERVER_URL: http://server:8080
    networks:
      - queue-demo-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://server:8080
    networks:
      - queue-demo-network
    profiles:
      - manual

networks:
  queue-demo-network:
    driver: bridge