---
services:
  gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    networks:
      - a2a-network

  server:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.server
      args:
        EXAMPLE_PATH: examples/artifacts-with-default-handlers
        COMPONENT: server
    volumes:
      - ./server/artifacts:/app/artifacts
    environment:
      ENVIRONMENT: development
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_CAPABILITIES_STREAMING: true
      A2A_ARTIFACTS_SERVER_HOST: server
      A2A_ARTIFACTS_SERVER_PORT: 8081
      A2A_ARTIFACTS_STORAGE_BASE_URL: http://server:8081
      A2A_AGENT_CLIENT_PROVIDER: ${A2A_AGENT_CLIENT_PROVIDER}
      A2A_AGENT_CLIENT_MODEL: ${A2A_AGENT_CLIENT_MODEL}
      A2A_AGENT_CLIENT_BASE_URL: ${A2A_AGENT_CLIENT_BASE_URL}
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - a2a-network

  client:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.client
      args:
        EXAMPLE_PATH: examples/artifacts-with-default-handlers
        COMPONENT: client
    volumes:
      - ./client/downloads:/app/downloads
      - ./client/uploads:/app/uploads
    environment:
      SERVER_URL: http://server:8080
    depends_on:
      server:
        condition: service_healthy
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://server:8080
    networks:
      - a2a-network
    profiles:
      - manual

networks:
  a2a-network:
    driver: bridge
