---
services:
  inference-gateway:
    image: ghcr.io/inference-gateway/inference-gateway:latest
    pull_policy: always
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}
      COHERE_API_KEY: ${COHERE_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      LOG_LEVEL: info
    networks:
      - a2a-network

  server:
    build:
      context: ./server
      args:
        AGENT_NAME: ai-powered-agent
        AGENT_DESCRIPTION: An AI-powered A2A server with weather and time tools
        AGENT_VERSION: 0.1.0
    ports:
      - "8080:8080"
    depends_on:
      - inference-gateway
    environment:
      ENVIRONMENT: development
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_CAPABILITIES_STREAMING: true
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
      A2A_AGENT_CLIENT_BASE_URL: http://inference-gateway:8080/v1
      A2A_AGENT_CLIENT_PROVIDER: ${A2A_AGENT_CLIENT_PROVIDER}
      A2A_AGENT_CLIENT_MODEL: ${A2A_AGENT_CLIENT_MODEL}
    networks:
      - a2a-network

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080
    networks:
      - a2a-network
    command: sh -c "sleep 5 && /app/client"

networks:
  a2a-network:
    driver: bridge