---
services:
  server:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.server
      args:
        AGENT_NAME: artifacts-filesystem-agent
        AGENT_DESCRIPTION: An agent that creates and serves artifacts using filesystem storage
        AGENT_VERSION: 0.1.0
        LD_FLAGS: "-w -s -X 'main.AgentName=${AGENT_NAME}' -X 'main.AgentDescription=${AGENT_DESCRIPTION}' -X 'main.AgentVersion=${AGENT_VERSION}'"
        EXAMPLE_PATH: examples/artifacts-filesystem
        COMPONENT: server
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      ENVIRONMENT: development
      A2A_AGENT_NAME: artifacts-filesystem-agent
      A2A_AGENT_DESCRIPTION: An agent that creates and serves artifacts using filesystem storage
      A2A_AGENT_VERSION: 0.1.0
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_CAPABILITIES_STREAMING: false
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
      A2A_ARTIFACTS_ENABLE: true
      A2A_ARTIFACTS_STORAGE_PROVIDER: filesystem
      A2A_ARTIFACTS_STORAGE_BASE_PATH: ./artifacts
      A2A_ARTIFACTS_SERVER_PORT: 8081
      A2A_ARTIFACTS_SERVER_HOST: server
    volumes:
      - ./server/artifacts:/app/artifacts
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - http://localhost:8080/health
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - a2a-network

  client:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.client
      args:
        LD_FLAGS: "-w -s"
        EXAMPLE_PATH: examples/artifacts-filesystem
        COMPONENT: client
    depends_on:
      server:
        condition: service_healthy
    environment:
      SERVER_URL: http://server:8080
      ARTIFACTS_URL: http://server:8081
      DOWNLOADS_DIR: /app/downloads
    volumes:
      - ./client/downloads:/app/downloads
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://server:8080
    networks:
      - a2a-network
    profiles:
      - manual

networks:
  a2a-network:
    driver: bridge
