// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"net/http"
	"sync"

	"github.com/inference-gateway/a2a/adk/server"
)

type FakeHTTPServer struct {
	HandlerStub        func() http.Handler
	handlerMutex       sync.RWMutex
	handlerArgsForCall []struct {
	}
	handlerReturns struct {
		result1 http.Handler
	}
	handlerReturnsOnCall map[int]struct {
		result1 http.Handler
	}
	ListenAndServeStub        func() error
	listenAndServeMutex       sync.RWMutex
	listenAndServeArgsForCall []struct {
	}
	listenAndServeReturns struct {
		result1 error
	}
	listenAndServeReturnsOnCall map[int]struct {
		result1 error
	}
	ShutdownStub        func(context.Context) error
	shutdownMutex       sync.RWMutex
	shutdownArgsForCall []struct {
		arg1 context.Context
	}
	shutdownReturns struct {
		result1 error
	}
	shutdownReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHTTPServer) Handler() http.Handler {
	fake.handlerMutex.Lock()
	ret, specificReturn := fake.handlerReturnsOnCall[len(fake.handlerArgsForCall)]
	fake.handlerArgsForCall = append(fake.handlerArgsForCall, struct {
	}{})
	stub := fake.HandlerStub
	fakeReturns := fake.handlerReturns
	fake.recordInvocation("Handler", []interface{}{})
	fake.handlerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHTTPServer) HandlerCallCount() int {
	fake.handlerMutex.RLock()
	defer fake.handlerMutex.RUnlock()
	return len(fake.handlerArgsForCall)
}

func (fake *FakeHTTPServer) HandlerCalls(stub func() http.Handler) {
	fake.handlerMutex.Lock()
	defer fake.handlerMutex.Unlock()
	fake.HandlerStub = stub
}

func (fake *FakeHTTPServer) HandlerReturns(result1 http.Handler) {
	fake.handlerMutex.Lock()
	defer fake.handlerMutex.Unlock()
	fake.HandlerStub = nil
	fake.handlerReturns = struct {
		result1 http.Handler
	}{result1}
}

func (fake *FakeHTTPServer) HandlerReturnsOnCall(i int, result1 http.Handler) {
	fake.handlerMutex.Lock()
	defer fake.handlerMutex.Unlock()
	fake.HandlerStub = nil
	if fake.handlerReturnsOnCall == nil {
		fake.handlerReturnsOnCall = make(map[int]struct {
			result1 http.Handler
		})
	}
	fake.handlerReturnsOnCall[i] = struct {
		result1 http.Handler
	}{result1}
}

func (fake *FakeHTTPServer) ListenAndServe() error {
	fake.listenAndServeMutex.Lock()
	ret, specificReturn := fake.listenAndServeReturnsOnCall[len(fake.listenAndServeArgsForCall)]
	fake.listenAndServeArgsForCall = append(fake.listenAndServeArgsForCall, struct {
	}{})
	stub := fake.ListenAndServeStub
	fakeReturns := fake.listenAndServeReturns
	fake.recordInvocation("ListenAndServe", []interface{}{})
	fake.listenAndServeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHTTPServer) ListenAndServeCallCount() int {
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	return len(fake.listenAndServeArgsForCall)
}

func (fake *FakeHTTPServer) ListenAndServeCalls(stub func() error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = stub
}

func (fake *FakeHTTPServer) ListenAndServeReturns(result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	fake.listenAndServeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeHTTPServer) ListenAndServeReturnsOnCall(i int, result1 error) {
	fake.listenAndServeMutex.Lock()
	defer fake.listenAndServeMutex.Unlock()
	fake.ListenAndServeStub = nil
	if fake.listenAndServeReturnsOnCall == nil {
		fake.listenAndServeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.listenAndServeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeHTTPServer) Shutdown(arg1 context.Context) error {
	fake.shutdownMutex.Lock()
	ret, specificReturn := fake.shutdownReturnsOnCall[len(fake.shutdownArgsForCall)]
	fake.shutdownArgsForCall = append(fake.shutdownArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ShutdownStub
	fakeReturns := fake.shutdownReturns
	fake.recordInvocation("Shutdown", []interface{}{arg1})
	fake.shutdownMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeHTTPServer) ShutdownCallCount() int {
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	return len(fake.shutdownArgsForCall)
}

func (fake *FakeHTTPServer) ShutdownCalls(stub func(context.Context) error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = stub
}

func (fake *FakeHTTPServer) ShutdownArgsForCall(i int) context.Context {
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	argsForCall := fake.shutdownArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeHTTPServer) ShutdownReturns(result1 error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = nil
	fake.shutdownReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeHTTPServer) ShutdownReturnsOnCall(i int, result1 error) {
	fake.shutdownMutex.Lock()
	defer fake.shutdownMutex.Unlock()
	fake.ShutdownStub = nil
	if fake.shutdownReturnsOnCall == nil {
		fake.shutdownReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.shutdownReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeHTTPServer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handlerMutex.RLock()
	defer fake.handlerMutex.RUnlock()
	fake.listenAndServeMutex.RLock()
	defer fake.listenAndServeMutex.RUnlock()
	fake.shutdownMutex.RLock()
	defer fake.shutdownMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHTTPServer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.HTTPServer = new(FakeHTTPServer)
