// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"net/http"
	"sync"
	"time"

	"github.com/inference-gateway/a2a/adk"
	"github.com/inference-gateway/a2a/adk/client"
	"go.uber.org/zap"
)

type FakeA2AClient struct {
	CancelTaskStub        func(context.Context, adk.TaskIdParams) (*adk.JSONRPCSuccessResponse, error)
	cancelTaskMutex       sync.RWMutex
	cancelTaskArgsForCall []struct {
		arg1 context.Context
		arg2 adk.TaskIdParams
	}
	cancelTaskReturns struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	cancelTaskReturnsOnCall map[int]struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	GetAgentCardStub        func(context.Context) (*adk.AgentCard, error)
	getAgentCardMutex       sync.RWMutex
	getAgentCardArgsForCall []struct {
		arg1 context.Context
	}
	getAgentCardReturns struct {
		result1 *adk.AgentCard
		result2 error
	}
	getAgentCardReturnsOnCall map[int]struct {
		result1 *adk.AgentCard
		result2 error
	}
	GetBaseURLStub        func() string
	getBaseURLMutex       sync.RWMutex
	getBaseURLArgsForCall []struct {
	}
	getBaseURLReturns struct {
		result1 string
	}
	getBaseURLReturnsOnCall map[int]struct {
		result1 string
	}
	GetLoggerStub        func() *zap.Logger
	getLoggerMutex       sync.RWMutex
	getLoggerArgsForCall []struct {
	}
	getLoggerReturns struct {
		result1 *zap.Logger
	}
	getLoggerReturnsOnCall map[int]struct {
		result1 *zap.Logger
	}
	GetTaskStub        func(context.Context, adk.TaskQueryParams) (*adk.JSONRPCSuccessResponse, error)
	getTaskMutex       sync.RWMutex
	getTaskArgsForCall []struct {
		arg1 context.Context
		arg2 adk.TaskQueryParams
	}
	getTaskReturns struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	getTaskReturnsOnCall map[int]struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	SendTaskStub        func(context.Context, adk.MessageSendParams) (*adk.JSONRPCSuccessResponse, error)
	sendTaskMutex       sync.RWMutex
	sendTaskArgsForCall []struct {
		arg1 context.Context
		arg2 adk.MessageSendParams
	}
	sendTaskReturns struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	sendTaskReturnsOnCall map[int]struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}
	SendTaskStreamingStub        func(context.Context, adk.MessageSendParams, chan<- interface{}) error
	sendTaskStreamingMutex       sync.RWMutex
	sendTaskStreamingArgsForCall []struct {
		arg1 context.Context
		arg2 adk.MessageSendParams
		arg3 chan<- interface{}
	}
	sendTaskStreamingReturns struct {
		result1 error
	}
	sendTaskStreamingReturnsOnCall map[int]struct {
		result1 error
	}
	SetHTTPClientStub        func(*http.Client)
	setHTTPClientMutex       sync.RWMutex
	setHTTPClientArgsForCall []struct {
		arg1 *http.Client
	}
	SetLoggerStub        func(*zap.Logger)
	setLoggerMutex       sync.RWMutex
	setLoggerArgsForCall []struct {
		arg1 *zap.Logger
	}
	SetTimeoutStub        func(time.Duration)
	setTimeoutMutex       sync.RWMutex
	setTimeoutArgsForCall []struct {
		arg1 time.Duration
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeA2AClient) CancelTask(arg1 context.Context, arg2 adk.TaskIdParams) (*adk.JSONRPCSuccessResponse, error) {
	fake.cancelTaskMutex.Lock()
	ret, specificReturn := fake.cancelTaskReturnsOnCall[len(fake.cancelTaskArgsForCall)]
	fake.cancelTaskArgsForCall = append(fake.cancelTaskArgsForCall, struct {
		arg1 context.Context
		arg2 adk.TaskIdParams
	}{arg1, arg2})
	stub := fake.CancelTaskStub
	fakeReturns := fake.cancelTaskReturns
	fake.recordInvocation("CancelTask", []interface{}{arg1, arg2})
	fake.cancelTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeA2AClient) CancelTaskCallCount() int {
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	return len(fake.cancelTaskArgsForCall)
}

func (fake *FakeA2AClient) CancelTaskCalls(stub func(context.Context, adk.TaskIdParams) (*adk.JSONRPCSuccessResponse, error)) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = stub
}

func (fake *FakeA2AClient) CancelTaskArgsForCall(i int) (context.Context, adk.TaskIdParams) {
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	argsForCall := fake.cancelTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2AClient) CancelTaskReturns(result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = nil
	fake.cancelTaskReturns = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) CancelTaskReturnsOnCall(i int, result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.cancelTaskMutex.Lock()
	defer fake.cancelTaskMutex.Unlock()
	fake.CancelTaskStub = nil
	if fake.cancelTaskReturnsOnCall == nil {
		fake.cancelTaskReturnsOnCall = make(map[int]struct {
			result1 *adk.JSONRPCSuccessResponse
			result2 error
		})
	}
	fake.cancelTaskReturnsOnCall[i] = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) GetAgentCard(arg1 context.Context) (*adk.AgentCard, error) {
	fake.getAgentCardMutex.Lock()
	ret, specificReturn := fake.getAgentCardReturnsOnCall[len(fake.getAgentCardArgsForCall)]
	fake.getAgentCardArgsForCall = append(fake.getAgentCardArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.GetAgentCardStub
	fakeReturns := fake.getAgentCardReturns
	fake.recordInvocation("GetAgentCard", []interface{}{arg1})
	fake.getAgentCardMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeA2AClient) GetAgentCardCallCount() int {
	fake.getAgentCardMutex.RLock()
	defer fake.getAgentCardMutex.RUnlock()
	return len(fake.getAgentCardArgsForCall)
}

func (fake *FakeA2AClient) GetAgentCardCalls(stub func(context.Context) (*adk.AgentCard, error)) {
	fake.getAgentCardMutex.Lock()
	defer fake.getAgentCardMutex.Unlock()
	fake.GetAgentCardStub = stub
}

func (fake *FakeA2AClient) GetAgentCardArgsForCall(i int) context.Context {
	fake.getAgentCardMutex.RLock()
	defer fake.getAgentCardMutex.RUnlock()
	argsForCall := fake.getAgentCardArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AClient) GetAgentCardReturns(result1 *adk.AgentCard, result2 error) {
	fake.getAgentCardMutex.Lock()
	defer fake.getAgentCardMutex.Unlock()
	fake.GetAgentCardStub = nil
	fake.getAgentCardReturns = struct {
		result1 *adk.AgentCard
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) GetAgentCardReturnsOnCall(i int, result1 *adk.AgentCard, result2 error) {
	fake.getAgentCardMutex.Lock()
	defer fake.getAgentCardMutex.Unlock()
	fake.GetAgentCardStub = nil
	if fake.getAgentCardReturnsOnCall == nil {
		fake.getAgentCardReturnsOnCall = make(map[int]struct {
			result1 *adk.AgentCard
			result2 error
		})
	}
	fake.getAgentCardReturnsOnCall[i] = struct {
		result1 *adk.AgentCard
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) GetBaseURL() string {
	fake.getBaseURLMutex.Lock()
	ret, specificReturn := fake.getBaseURLReturnsOnCall[len(fake.getBaseURLArgsForCall)]
	fake.getBaseURLArgsForCall = append(fake.getBaseURLArgsForCall, struct {
	}{})
	stub := fake.GetBaseURLStub
	fakeReturns := fake.getBaseURLReturns
	fake.recordInvocation("GetBaseURL", []interface{}{})
	fake.getBaseURLMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AClient) GetBaseURLCallCount() int {
	fake.getBaseURLMutex.RLock()
	defer fake.getBaseURLMutex.RUnlock()
	return len(fake.getBaseURLArgsForCall)
}

func (fake *FakeA2AClient) GetBaseURLCalls(stub func() string) {
	fake.getBaseURLMutex.Lock()
	defer fake.getBaseURLMutex.Unlock()
	fake.GetBaseURLStub = stub
}

func (fake *FakeA2AClient) GetBaseURLReturns(result1 string) {
	fake.getBaseURLMutex.Lock()
	defer fake.getBaseURLMutex.Unlock()
	fake.GetBaseURLStub = nil
	fake.getBaseURLReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2AClient) GetBaseURLReturnsOnCall(i int, result1 string) {
	fake.getBaseURLMutex.Lock()
	defer fake.getBaseURLMutex.Unlock()
	fake.GetBaseURLStub = nil
	if fake.getBaseURLReturnsOnCall == nil {
		fake.getBaseURLReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getBaseURLReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeA2AClient) GetLogger() *zap.Logger {
	fake.getLoggerMutex.Lock()
	ret, specificReturn := fake.getLoggerReturnsOnCall[len(fake.getLoggerArgsForCall)]
	fake.getLoggerArgsForCall = append(fake.getLoggerArgsForCall, struct {
	}{})
	stub := fake.GetLoggerStub
	fakeReturns := fake.getLoggerReturns
	fake.recordInvocation("GetLogger", []interface{}{})
	fake.getLoggerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AClient) GetLoggerCallCount() int {
	fake.getLoggerMutex.RLock()
	defer fake.getLoggerMutex.RUnlock()
	return len(fake.getLoggerArgsForCall)
}

func (fake *FakeA2AClient) GetLoggerCalls(stub func() *zap.Logger) {
	fake.getLoggerMutex.Lock()
	defer fake.getLoggerMutex.Unlock()
	fake.GetLoggerStub = stub
}

func (fake *FakeA2AClient) GetLoggerReturns(result1 *zap.Logger) {
	fake.getLoggerMutex.Lock()
	defer fake.getLoggerMutex.Unlock()
	fake.GetLoggerStub = nil
	fake.getLoggerReturns = struct {
		result1 *zap.Logger
	}{result1}
}

func (fake *FakeA2AClient) GetLoggerReturnsOnCall(i int, result1 *zap.Logger) {
	fake.getLoggerMutex.Lock()
	defer fake.getLoggerMutex.Unlock()
	fake.GetLoggerStub = nil
	if fake.getLoggerReturnsOnCall == nil {
		fake.getLoggerReturnsOnCall = make(map[int]struct {
			result1 *zap.Logger
		})
	}
	fake.getLoggerReturnsOnCall[i] = struct {
		result1 *zap.Logger
	}{result1}
}

func (fake *FakeA2AClient) GetTask(arg1 context.Context, arg2 adk.TaskQueryParams) (*adk.JSONRPCSuccessResponse, error) {
	fake.getTaskMutex.Lock()
	ret, specificReturn := fake.getTaskReturnsOnCall[len(fake.getTaskArgsForCall)]
	fake.getTaskArgsForCall = append(fake.getTaskArgsForCall, struct {
		arg1 context.Context
		arg2 adk.TaskQueryParams
	}{arg1, arg2})
	stub := fake.GetTaskStub
	fakeReturns := fake.getTaskReturns
	fake.recordInvocation("GetTask", []interface{}{arg1, arg2})
	fake.getTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeA2AClient) GetTaskCallCount() int {
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	return len(fake.getTaskArgsForCall)
}

func (fake *FakeA2AClient) GetTaskCalls(stub func(context.Context, adk.TaskQueryParams) (*adk.JSONRPCSuccessResponse, error)) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = stub
}

func (fake *FakeA2AClient) GetTaskArgsForCall(i int) (context.Context, adk.TaskQueryParams) {
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	argsForCall := fake.getTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2AClient) GetTaskReturns(result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = nil
	fake.getTaskReturns = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) GetTaskReturnsOnCall(i int, result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = nil
	if fake.getTaskReturnsOnCall == nil {
		fake.getTaskReturnsOnCall = make(map[int]struct {
			result1 *adk.JSONRPCSuccessResponse
			result2 error
		})
	}
	fake.getTaskReturnsOnCall[i] = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) SendTask(arg1 context.Context, arg2 adk.MessageSendParams) (*adk.JSONRPCSuccessResponse, error) {
	fake.sendTaskMutex.Lock()
	ret, specificReturn := fake.sendTaskReturnsOnCall[len(fake.sendTaskArgsForCall)]
	fake.sendTaskArgsForCall = append(fake.sendTaskArgsForCall, struct {
		arg1 context.Context
		arg2 adk.MessageSendParams
	}{arg1, arg2})
	stub := fake.SendTaskStub
	fakeReturns := fake.sendTaskReturns
	fake.recordInvocation("SendTask", []interface{}{arg1, arg2})
	fake.sendTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeA2AClient) SendTaskCallCount() int {
	fake.sendTaskMutex.RLock()
	defer fake.sendTaskMutex.RUnlock()
	return len(fake.sendTaskArgsForCall)
}

func (fake *FakeA2AClient) SendTaskCalls(stub func(context.Context, adk.MessageSendParams) (*adk.JSONRPCSuccessResponse, error)) {
	fake.sendTaskMutex.Lock()
	defer fake.sendTaskMutex.Unlock()
	fake.SendTaskStub = stub
}

func (fake *FakeA2AClient) SendTaskArgsForCall(i int) (context.Context, adk.MessageSendParams) {
	fake.sendTaskMutex.RLock()
	defer fake.sendTaskMutex.RUnlock()
	argsForCall := fake.sendTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2AClient) SendTaskReturns(result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.sendTaskMutex.Lock()
	defer fake.sendTaskMutex.Unlock()
	fake.SendTaskStub = nil
	fake.sendTaskReturns = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) SendTaskReturnsOnCall(i int, result1 *adk.JSONRPCSuccessResponse, result2 error) {
	fake.sendTaskMutex.Lock()
	defer fake.sendTaskMutex.Unlock()
	fake.SendTaskStub = nil
	if fake.sendTaskReturnsOnCall == nil {
		fake.sendTaskReturnsOnCall = make(map[int]struct {
			result1 *adk.JSONRPCSuccessResponse
			result2 error
		})
	}
	fake.sendTaskReturnsOnCall[i] = struct {
		result1 *adk.JSONRPCSuccessResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AClient) SendTaskStreaming(arg1 context.Context, arg2 adk.MessageSendParams, arg3 chan<- interface{}) error {
	fake.sendTaskStreamingMutex.Lock()
	ret, specificReturn := fake.sendTaskStreamingReturnsOnCall[len(fake.sendTaskStreamingArgsForCall)]
	fake.sendTaskStreamingArgsForCall = append(fake.sendTaskStreamingArgsForCall, struct {
		arg1 context.Context
		arg2 adk.MessageSendParams
		arg3 chan<- interface{}
	}{arg1, arg2, arg3})
	stub := fake.SendTaskStreamingStub
	fakeReturns := fake.sendTaskStreamingReturns
	fake.recordInvocation("SendTaskStreaming", []interface{}{arg1, arg2, arg3})
	fake.sendTaskStreamingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AClient) SendTaskStreamingCallCount() int {
	fake.sendTaskStreamingMutex.RLock()
	defer fake.sendTaskStreamingMutex.RUnlock()
	return len(fake.sendTaskStreamingArgsForCall)
}

func (fake *FakeA2AClient) SendTaskStreamingCalls(stub func(context.Context, adk.MessageSendParams, chan<- interface{}) error) {
	fake.sendTaskStreamingMutex.Lock()
	defer fake.sendTaskStreamingMutex.Unlock()
	fake.SendTaskStreamingStub = stub
}

func (fake *FakeA2AClient) SendTaskStreamingArgsForCall(i int) (context.Context, adk.MessageSendParams, chan<- interface{}) {
	fake.sendTaskStreamingMutex.RLock()
	defer fake.sendTaskStreamingMutex.RUnlock()
	argsForCall := fake.sendTaskStreamingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeA2AClient) SendTaskStreamingReturns(result1 error) {
	fake.sendTaskStreamingMutex.Lock()
	defer fake.sendTaskStreamingMutex.Unlock()
	fake.SendTaskStreamingStub = nil
	fake.sendTaskStreamingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeA2AClient) SendTaskStreamingReturnsOnCall(i int, result1 error) {
	fake.sendTaskStreamingMutex.Lock()
	defer fake.sendTaskStreamingMutex.Unlock()
	fake.SendTaskStreamingStub = nil
	if fake.sendTaskStreamingReturnsOnCall == nil {
		fake.sendTaskStreamingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendTaskStreamingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeA2AClient) SetHTTPClient(arg1 *http.Client) {
	fake.setHTTPClientMutex.Lock()
	fake.setHTTPClientArgsForCall = append(fake.setHTTPClientArgsForCall, struct {
		arg1 *http.Client
	}{arg1})
	stub := fake.SetHTTPClientStub
	fake.recordInvocation("SetHTTPClient", []interface{}{arg1})
	fake.setHTTPClientMutex.Unlock()
	if stub != nil {
		fake.SetHTTPClientStub(arg1)
	}
}

func (fake *FakeA2AClient) SetHTTPClientCallCount() int {
	fake.setHTTPClientMutex.RLock()
	defer fake.setHTTPClientMutex.RUnlock()
	return len(fake.setHTTPClientArgsForCall)
}

func (fake *FakeA2AClient) SetHTTPClientCalls(stub func(*http.Client)) {
	fake.setHTTPClientMutex.Lock()
	defer fake.setHTTPClientMutex.Unlock()
	fake.SetHTTPClientStub = stub
}

func (fake *FakeA2AClient) SetHTTPClientArgsForCall(i int) *http.Client {
	fake.setHTTPClientMutex.RLock()
	defer fake.setHTTPClientMutex.RUnlock()
	argsForCall := fake.setHTTPClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AClient) SetLogger(arg1 *zap.Logger) {
	fake.setLoggerMutex.Lock()
	fake.setLoggerArgsForCall = append(fake.setLoggerArgsForCall, struct {
		arg1 *zap.Logger
	}{arg1})
	stub := fake.SetLoggerStub
	fake.recordInvocation("SetLogger", []interface{}{arg1})
	fake.setLoggerMutex.Unlock()
	if stub != nil {
		fake.SetLoggerStub(arg1)
	}
}

func (fake *FakeA2AClient) SetLoggerCallCount() int {
	fake.setLoggerMutex.RLock()
	defer fake.setLoggerMutex.RUnlock()
	return len(fake.setLoggerArgsForCall)
}

func (fake *FakeA2AClient) SetLoggerCalls(stub func(*zap.Logger)) {
	fake.setLoggerMutex.Lock()
	defer fake.setLoggerMutex.Unlock()
	fake.SetLoggerStub = stub
}

func (fake *FakeA2AClient) SetLoggerArgsForCall(i int) *zap.Logger {
	fake.setLoggerMutex.RLock()
	defer fake.setLoggerMutex.RUnlock()
	argsForCall := fake.setLoggerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AClient) SetTimeout(arg1 time.Duration) {
	fake.setTimeoutMutex.Lock()
	fake.setTimeoutArgsForCall = append(fake.setTimeoutArgsForCall, struct {
		arg1 time.Duration
	}{arg1})
	stub := fake.SetTimeoutStub
	fake.recordInvocation("SetTimeout", []interface{}{arg1})
	fake.setTimeoutMutex.Unlock()
	if stub != nil {
		fake.SetTimeoutStub(arg1)
	}
}

func (fake *FakeA2AClient) SetTimeoutCallCount() int {
	fake.setTimeoutMutex.RLock()
	defer fake.setTimeoutMutex.RUnlock()
	return len(fake.setTimeoutArgsForCall)
}

func (fake *FakeA2AClient) SetTimeoutCalls(stub func(time.Duration)) {
	fake.setTimeoutMutex.Lock()
	defer fake.setTimeoutMutex.Unlock()
	fake.SetTimeoutStub = stub
}

func (fake *FakeA2AClient) SetTimeoutArgsForCall(i int) time.Duration {
	fake.setTimeoutMutex.RLock()
	defer fake.setTimeoutMutex.RUnlock()
	argsForCall := fake.setTimeoutArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.cancelTaskMutex.RLock()
	defer fake.cancelTaskMutex.RUnlock()
	fake.getAgentCardMutex.RLock()
	defer fake.getAgentCardMutex.RUnlock()
	fake.getBaseURLMutex.RLock()
	defer fake.getBaseURLMutex.RUnlock()
	fake.getLoggerMutex.RLock()
	defer fake.getLoggerMutex.RUnlock()
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	fake.sendTaskMutex.RLock()
	defer fake.sendTaskMutex.RUnlock()
	fake.sendTaskStreamingMutex.RLock()
	defer fake.sendTaskStreamingMutex.RUnlock()
	fake.setHTTPClientMutex.RLock()
	defer fake.setHTTPClientMutex.RUnlock()
	fake.setLoggerMutex.RLock()
	defer fake.setLoggerMutex.RUnlock()
	fake.setTimeoutMutex.RLock()
	defer fake.setTimeoutMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeA2AClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.A2AClient = new(FakeA2AClient)
