// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/inference-gateway/adk/server"
	"github.com/inference-gateway/adk/types"
)

type FakeTaskHandler struct {
	GetAgentStub        func() server.OpenAICompatibleAgent
	getAgentMutex       sync.RWMutex
	getAgentArgsForCall []struct {
	}
	getAgentReturns struct {
		result1 server.OpenAICompatibleAgent
	}
	getAgentReturnsOnCall map[int]struct {
		result1 server.OpenAICompatibleAgent
	}
	HandleTaskStub        func(context.Context, *types.Task, *types.Message) (*types.Task, error)
	handleTaskMutex       sync.RWMutex
	handleTaskArgsForCall []struct {
		arg1 context.Context
		arg2 *types.Task
		arg3 *types.Message
	}
	handleTaskReturns struct {
		result1 *types.Task
		result2 error
	}
	handleTaskReturnsOnCall map[int]struct {
		result1 *types.Task
		result2 error
	}
	RequestInputStub        func(string) *types.Message
	requestInputMutex       sync.RWMutex
	requestInputArgsForCall []struct {
		arg1 string
	}
	requestInputReturns struct {
		result1 *types.Message
	}
	requestInputReturnsOnCall map[int]struct {
		result1 *types.Message
	}
	SetAgentStub        func(server.OpenAICompatibleAgent)
	setAgentMutex       sync.RWMutex
	setAgentArgsForCall []struct {
		arg1 server.OpenAICompatibleAgent
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTaskHandler) GetAgent() server.OpenAICompatibleAgent {
	fake.getAgentMutex.Lock()
	ret, specificReturn := fake.getAgentReturnsOnCall[len(fake.getAgentArgsForCall)]
	fake.getAgentArgsForCall = append(fake.getAgentArgsForCall, struct {
	}{})
	stub := fake.GetAgentStub
	fakeReturns := fake.getAgentReturns
	fake.recordInvocation("GetAgent", []interface{}{})
	fake.getAgentMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskHandler) GetAgentCallCount() int {
	fake.getAgentMutex.RLock()
	defer fake.getAgentMutex.RUnlock()
	return len(fake.getAgentArgsForCall)
}

func (fake *FakeTaskHandler) GetAgentCalls(stub func() server.OpenAICompatibleAgent) {
	fake.getAgentMutex.Lock()
	defer fake.getAgentMutex.Unlock()
	fake.GetAgentStub = stub
}

func (fake *FakeTaskHandler) GetAgentReturns(result1 server.OpenAICompatibleAgent) {
	fake.getAgentMutex.Lock()
	defer fake.getAgentMutex.Unlock()
	fake.GetAgentStub = nil
	fake.getAgentReturns = struct {
		result1 server.OpenAICompatibleAgent
	}{result1}
}

func (fake *FakeTaskHandler) GetAgentReturnsOnCall(i int, result1 server.OpenAICompatibleAgent) {
	fake.getAgentMutex.Lock()
	defer fake.getAgentMutex.Unlock()
	fake.GetAgentStub = nil
	if fake.getAgentReturnsOnCall == nil {
		fake.getAgentReturnsOnCall = make(map[int]struct {
			result1 server.OpenAICompatibleAgent
		})
	}
	fake.getAgentReturnsOnCall[i] = struct {
		result1 server.OpenAICompatibleAgent
	}{result1}
}

func (fake *FakeTaskHandler) HandleTask(arg1 context.Context, arg2 *types.Task, arg3 *types.Message) (*types.Task, error) {
	fake.handleTaskMutex.Lock()
	ret, specificReturn := fake.handleTaskReturnsOnCall[len(fake.handleTaskArgsForCall)]
	fake.handleTaskArgsForCall = append(fake.handleTaskArgsForCall, struct {
		arg1 context.Context
		arg2 *types.Task
		arg3 *types.Message
	}{arg1, arg2, arg3})
	stub := fake.HandleTaskStub
	fakeReturns := fake.handleTaskReturns
	fake.recordInvocation("HandleTask", []interface{}{arg1, arg2, arg3})
	fake.handleTaskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTaskHandler) HandleTaskCallCount() int {
	fake.handleTaskMutex.RLock()
	defer fake.handleTaskMutex.RUnlock()
	return len(fake.handleTaskArgsForCall)
}

func (fake *FakeTaskHandler) HandleTaskCalls(stub func(context.Context, *types.Task, *types.Message) (*types.Task, error)) {
	fake.handleTaskMutex.Lock()
	defer fake.handleTaskMutex.Unlock()
	fake.HandleTaskStub = stub
}

func (fake *FakeTaskHandler) HandleTaskArgsForCall(i int) (context.Context, *types.Task, *types.Message) {
	fake.handleTaskMutex.RLock()
	defer fake.handleTaskMutex.RUnlock()
	argsForCall := fake.handleTaskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeTaskHandler) HandleTaskReturns(result1 *types.Task, result2 error) {
	fake.handleTaskMutex.Lock()
	defer fake.handleTaskMutex.Unlock()
	fake.HandleTaskStub = nil
	fake.handleTaskReturns = struct {
		result1 *types.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskHandler) HandleTaskReturnsOnCall(i int, result1 *types.Task, result2 error) {
	fake.handleTaskMutex.Lock()
	defer fake.handleTaskMutex.Unlock()
	fake.HandleTaskStub = nil
	if fake.handleTaskReturnsOnCall == nil {
		fake.handleTaskReturnsOnCall = make(map[int]struct {
			result1 *types.Task
			result2 error
		})
	}
	fake.handleTaskReturnsOnCall[i] = struct {
		result1 *types.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeTaskHandler) RequestInput(arg1 string) *types.Message {
	fake.requestInputMutex.Lock()
	ret, specificReturn := fake.requestInputReturnsOnCall[len(fake.requestInputArgsForCall)]
	fake.requestInputArgsForCall = append(fake.requestInputArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.RequestInputStub
	fakeReturns := fake.requestInputReturns
	fake.recordInvocation("RequestInput", []interface{}{arg1})
	fake.requestInputMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTaskHandler) RequestInputCallCount() int {
	fake.requestInputMutex.RLock()
	defer fake.requestInputMutex.RUnlock()
	return len(fake.requestInputArgsForCall)
}

func (fake *FakeTaskHandler) RequestInputCalls(stub func(string) *types.Message) {
	fake.requestInputMutex.Lock()
	defer fake.requestInputMutex.Unlock()
	fake.RequestInputStub = stub
}

func (fake *FakeTaskHandler) RequestInputArgsForCall(i int) string {
	fake.requestInputMutex.RLock()
	defer fake.requestInputMutex.RUnlock()
	argsForCall := fake.requestInputArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskHandler) RequestInputReturns(result1 *types.Message) {
	fake.requestInputMutex.Lock()
	defer fake.requestInputMutex.Unlock()
	fake.RequestInputStub = nil
	fake.requestInputReturns = struct {
		result1 *types.Message
	}{result1}
}

func (fake *FakeTaskHandler) RequestInputReturnsOnCall(i int, result1 *types.Message) {
	fake.requestInputMutex.Lock()
	defer fake.requestInputMutex.Unlock()
	fake.RequestInputStub = nil
	if fake.requestInputReturnsOnCall == nil {
		fake.requestInputReturnsOnCall = make(map[int]struct {
			result1 *types.Message
		})
	}
	fake.requestInputReturnsOnCall[i] = struct {
		result1 *types.Message
	}{result1}
}

func (fake *FakeTaskHandler) SetAgent(arg1 server.OpenAICompatibleAgent) {
	fake.setAgentMutex.Lock()
	fake.setAgentArgsForCall = append(fake.setAgentArgsForCall, struct {
		arg1 server.OpenAICompatibleAgent
	}{arg1})
	stub := fake.SetAgentStub
	fake.recordInvocation("SetAgent", []interface{}{arg1})
	fake.setAgentMutex.Unlock()
	if stub != nil {
		fake.SetAgentStub(arg1)
	}
}

func (fake *FakeTaskHandler) SetAgentCallCount() int {
	fake.setAgentMutex.RLock()
	defer fake.setAgentMutex.RUnlock()
	return len(fake.setAgentArgsForCall)
}

func (fake *FakeTaskHandler) SetAgentCalls(stub func(server.OpenAICompatibleAgent)) {
	fake.setAgentMutex.Lock()
	defer fake.setAgentMutex.Unlock()
	fake.SetAgentStub = stub
}

func (fake *FakeTaskHandler) SetAgentArgsForCall(i int) server.OpenAICompatibleAgent {
	fake.setAgentMutex.RLock()
	defer fake.setAgentMutex.RUnlock()
	argsForCall := fake.setAgentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTaskHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAgentMutex.RLock()
	defer fake.getAgentMutex.RUnlock()
	fake.handleTaskMutex.RLock()
	defer fake.handleTaskMutex.RUnlock()
	fake.requestInputMutex.RLock()
	defer fake.requestInputMutex.RUnlock()
	fake.setAgentMutex.RLock()
	defer fake.setAgentMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTaskHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.TaskHandler = new(FakeTaskHandler)
