// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/inference-gateway/adk/server"
	"github.com/inference-gateway/adk/types"
	"go.uber.org/zap"
)

type FakeA2AServerBuilder struct {
	BuildStub        func() (server.A2AServer, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
	}
	buildReturns struct {
		result1 server.A2AServer
		result2 error
	}
	buildReturnsOnCall map[int]struct {
		result1 server.A2AServer
		result2 error
	}
	WithAgentStub        func(server.OpenAICompatibleAgent) server.A2AServerBuilder
	withAgentMutex       sync.RWMutex
	withAgentArgsForCall []struct {
		arg1 server.OpenAICompatibleAgent
	}
	withAgentReturns struct {
		result1 server.A2AServerBuilder
	}
	withAgentReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithAgentCardStub        func(types.AgentCard) server.A2AServerBuilder
	withAgentCardMutex       sync.RWMutex
	withAgentCardArgsForCall []struct {
		arg1 types.AgentCard
	}
	withAgentCardReturns struct {
		result1 server.A2AServerBuilder
	}
	withAgentCardReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithAgentCardFromFileStub        func(string, map[string]any) server.A2AServerBuilder
	withAgentCardFromFileMutex       sync.RWMutex
	withAgentCardFromFileArgsForCall []struct {
		arg1 string
		arg2 map[string]any
	}
	withAgentCardFromFileReturns struct {
		result1 server.A2AServerBuilder
	}
	withAgentCardFromFileReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithArtifactsServerStub        func(server.ArtifactsServerBuilder) server.A2AServerBuilder
	withArtifactsServerMutex       sync.RWMutex
	withArtifactsServerArgsForCall []struct {
		arg1 server.ArtifactsServerBuilder
	}
	withArtifactsServerReturns struct {
		result1 server.A2AServerBuilder
	}
	withArtifactsServerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithBackgroundTaskHandlerStub        func(server.TaskHandler) server.A2AServerBuilder
	withBackgroundTaskHandlerMutex       sync.RWMutex
	withBackgroundTaskHandlerArgsForCall []struct {
		arg1 server.TaskHandler
	}
	withBackgroundTaskHandlerReturns struct {
		result1 server.A2AServerBuilder
	}
	withBackgroundTaskHandlerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithDefaultBackgroundTaskHandlerStub        func() server.A2AServerBuilder
	withDefaultBackgroundTaskHandlerMutex       sync.RWMutex
	withDefaultBackgroundTaskHandlerArgsForCall []struct {
	}
	withDefaultBackgroundTaskHandlerReturns struct {
		result1 server.A2AServerBuilder
	}
	withDefaultBackgroundTaskHandlerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithDefaultStreamingTaskHandlerStub        func() server.A2AServerBuilder
	withDefaultStreamingTaskHandlerMutex       sync.RWMutex
	withDefaultStreamingTaskHandlerArgsForCall []struct {
	}
	withDefaultStreamingTaskHandlerReturns struct {
		result1 server.A2AServerBuilder
	}
	withDefaultStreamingTaskHandlerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithDefaultTaskHandlersStub        func() server.A2AServerBuilder
	withDefaultTaskHandlersMutex       sync.RWMutex
	withDefaultTaskHandlersArgsForCall []struct {
	}
	withDefaultTaskHandlersReturns struct {
		result1 server.A2AServerBuilder
	}
	withDefaultTaskHandlersReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithLoggerStub        func(*zap.Logger) server.A2AServerBuilder
	withLoggerMutex       sync.RWMutex
	withLoggerArgsForCall []struct {
		arg1 *zap.Logger
	}
	withLoggerReturns struct {
		result1 server.A2AServerBuilder
	}
	withLoggerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithStreamingTaskHandlerStub        func(server.StreamableTaskHandler) server.A2AServerBuilder
	withStreamingTaskHandlerMutex       sync.RWMutex
	withStreamingTaskHandlerArgsForCall []struct {
		arg1 server.StreamableTaskHandler
	}
	withStreamingTaskHandlerReturns struct {
		result1 server.A2AServerBuilder
	}
	withStreamingTaskHandlerReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	WithTaskResultProcessorStub        func(server.TaskResultProcessor) server.A2AServerBuilder
	withTaskResultProcessorMutex       sync.RWMutex
	withTaskResultProcessorArgsForCall []struct {
		arg1 server.TaskResultProcessor
	}
	withTaskResultProcessorReturns struct {
		result1 server.A2AServerBuilder
	}
	withTaskResultProcessorReturnsOnCall map[int]struct {
		result1 server.A2AServerBuilder
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeA2AServerBuilder) Build() (server.A2AServer, error) {
	fake.buildMutex.Lock()
	ret, specificReturn := fake.buildReturnsOnCall[len(fake.buildArgsForCall)]
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
	}{})
	stub := fake.BuildStub
	fakeReturns := fake.buildReturns
	fake.recordInvocation("Build", []interface{}{})
	fake.buildMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeA2AServerBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeA2AServerBuilder) BuildCalls(stub func() (server.A2AServer, error)) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = stub
}

func (fake *FakeA2AServerBuilder) BuildReturns(result1 server.A2AServer, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	fake.buildReturns = struct {
		result1 server.A2AServer
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AServerBuilder) BuildReturnsOnCall(i int, result1 server.A2AServer, result2 error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.BuildStub = nil
	if fake.buildReturnsOnCall == nil {
		fake.buildReturnsOnCall = make(map[int]struct {
			result1 server.A2AServer
			result2 error
		})
	}
	fake.buildReturnsOnCall[i] = struct {
		result1 server.A2AServer
		result2 error
	}{result1, result2}
}

func (fake *FakeA2AServerBuilder) WithAgent(arg1 server.OpenAICompatibleAgent) server.A2AServerBuilder {
	fake.withAgentMutex.Lock()
	ret, specificReturn := fake.withAgentReturnsOnCall[len(fake.withAgentArgsForCall)]
	fake.withAgentArgsForCall = append(fake.withAgentArgsForCall, struct {
		arg1 server.OpenAICompatibleAgent
	}{arg1})
	stub := fake.WithAgentStub
	fakeReturns := fake.withAgentReturns
	fake.recordInvocation("WithAgent", []interface{}{arg1})
	fake.withAgentMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithAgentCallCount() int {
	fake.withAgentMutex.RLock()
	defer fake.withAgentMutex.RUnlock()
	return len(fake.withAgentArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithAgentCalls(stub func(server.OpenAICompatibleAgent) server.A2AServerBuilder) {
	fake.withAgentMutex.Lock()
	defer fake.withAgentMutex.Unlock()
	fake.WithAgentStub = stub
}

func (fake *FakeA2AServerBuilder) WithAgentArgsForCall(i int) server.OpenAICompatibleAgent {
	fake.withAgentMutex.RLock()
	defer fake.withAgentMutex.RUnlock()
	argsForCall := fake.withAgentArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithAgentReturns(result1 server.A2AServerBuilder) {
	fake.withAgentMutex.Lock()
	defer fake.withAgentMutex.Unlock()
	fake.WithAgentStub = nil
	fake.withAgentReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithAgentReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withAgentMutex.Lock()
	defer fake.withAgentMutex.Unlock()
	fake.WithAgentStub = nil
	if fake.withAgentReturnsOnCall == nil {
		fake.withAgentReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withAgentReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithAgentCard(arg1 types.AgentCard) server.A2AServerBuilder {
	fake.withAgentCardMutex.Lock()
	ret, specificReturn := fake.withAgentCardReturnsOnCall[len(fake.withAgentCardArgsForCall)]
	fake.withAgentCardArgsForCall = append(fake.withAgentCardArgsForCall, struct {
		arg1 types.AgentCard
	}{arg1})
	stub := fake.WithAgentCardStub
	fakeReturns := fake.withAgentCardReturns
	fake.recordInvocation("WithAgentCard", []interface{}{arg1})
	fake.withAgentCardMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithAgentCardCallCount() int {
	fake.withAgentCardMutex.RLock()
	defer fake.withAgentCardMutex.RUnlock()
	return len(fake.withAgentCardArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithAgentCardCalls(stub func(types.AgentCard) server.A2AServerBuilder) {
	fake.withAgentCardMutex.Lock()
	defer fake.withAgentCardMutex.Unlock()
	fake.WithAgentCardStub = stub
}

func (fake *FakeA2AServerBuilder) WithAgentCardArgsForCall(i int) types.AgentCard {
	fake.withAgentCardMutex.RLock()
	defer fake.withAgentCardMutex.RUnlock()
	argsForCall := fake.withAgentCardArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithAgentCardReturns(result1 server.A2AServerBuilder) {
	fake.withAgentCardMutex.Lock()
	defer fake.withAgentCardMutex.Unlock()
	fake.WithAgentCardStub = nil
	fake.withAgentCardReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithAgentCardReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withAgentCardMutex.Lock()
	defer fake.withAgentCardMutex.Unlock()
	fake.WithAgentCardStub = nil
	if fake.withAgentCardReturnsOnCall == nil {
		fake.withAgentCardReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withAgentCardReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFile(arg1 string, arg2 map[string]any) server.A2AServerBuilder {
	fake.withAgentCardFromFileMutex.Lock()
	ret, specificReturn := fake.withAgentCardFromFileReturnsOnCall[len(fake.withAgentCardFromFileArgsForCall)]
	fake.withAgentCardFromFileArgsForCall = append(fake.withAgentCardFromFileArgsForCall, struct {
		arg1 string
		arg2 map[string]any
	}{arg1, arg2})
	stub := fake.WithAgentCardFromFileStub
	fakeReturns := fake.withAgentCardFromFileReturns
	fake.recordInvocation("WithAgentCardFromFile", []interface{}{arg1, arg2})
	fake.withAgentCardFromFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFileCallCount() int {
	fake.withAgentCardFromFileMutex.RLock()
	defer fake.withAgentCardFromFileMutex.RUnlock()
	return len(fake.withAgentCardFromFileArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFileCalls(stub func(string, map[string]any) server.A2AServerBuilder) {
	fake.withAgentCardFromFileMutex.Lock()
	defer fake.withAgentCardFromFileMutex.Unlock()
	fake.WithAgentCardFromFileStub = stub
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFileArgsForCall(i int) (string, map[string]any) {
	fake.withAgentCardFromFileMutex.RLock()
	defer fake.withAgentCardFromFileMutex.RUnlock()
	argsForCall := fake.withAgentCardFromFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFileReturns(result1 server.A2AServerBuilder) {
	fake.withAgentCardFromFileMutex.Lock()
	defer fake.withAgentCardFromFileMutex.Unlock()
	fake.WithAgentCardFromFileStub = nil
	fake.withAgentCardFromFileReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithAgentCardFromFileReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withAgentCardFromFileMutex.Lock()
	defer fake.withAgentCardFromFileMutex.Unlock()
	fake.WithAgentCardFromFileStub = nil
	if fake.withAgentCardFromFileReturnsOnCall == nil {
		fake.withAgentCardFromFileReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withAgentCardFromFileReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithArtifactsServer(arg1 server.ArtifactsServerBuilder) server.A2AServerBuilder {
	fake.withArtifactsServerMutex.Lock()
	ret, specificReturn := fake.withArtifactsServerReturnsOnCall[len(fake.withArtifactsServerArgsForCall)]
	fake.withArtifactsServerArgsForCall = append(fake.withArtifactsServerArgsForCall, struct {
		arg1 server.ArtifactsServerBuilder
	}{arg1})
	stub := fake.WithArtifactsServerStub
	fakeReturns := fake.withArtifactsServerReturns
	fake.recordInvocation("WithArtifactsServer", []interface{}{arg1})
	fake.withArtifactsServerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithArtifactsServerCallCount() int {
	fake.withArtifactsServerMutex.RLock()
	defer fake.withArtifactsServerMutex.RUnlock()
	return len(fake.withArtifactsServerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithArtifactsServerCalls(stub func(server.ArtifactsServerBuilder) server.A2AServerBuilder) {
	fake.withArtifactsServerMutex.Lock()
	defer fake.withArtifactsServerMutex.Unlock()
	fake.WithArtifactsServerStub = stub
}

func (fake *FakeA2AServerBuilder) WithArtifactsServerArgsForCall(i int) server.ArtifactsServerBuilder {
	fake.withArtifactsServerMutex.RLock()
	defer fake.withArtifactsServerMutex.RUnlock()
	argsForCall := fake.withArtifactsServerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithArtifactsServerReturns(result1 server.A2AServerBuilder) {
	fake.withArtifactsServerMutex.Lock()
	defer fake.withArtifactsServerMutex.Unlock()
	fake.WithArtifactsServerStub = nil
	fake.withArtifactsServerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithArtifactsServerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withArtifactsServerMutex.Lock()
	defer fake.withArtifactsServerMutex.Unlock()
	fake.WithArtifactsServerStub = nil
	if fake.withArtifactsServerReturnsOnCall == nil {
		fake.withArtifactsServerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withArtifactsServerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandler(arg1 server.TaskHandler) server.A2AServerBuilder {
	fake.withBackgroundTaskHandlerMutex.Lock()
	ret, specificReturn := fake.withBackgroundTaskHandlerReturnsOnCall[len(fake.withBackgroundTaskHandlerArgsForCall)]
	fake.withBackgroundTaskHandlerArgsForCall = append(fake.withBackgroundTaskHandlerArgsForCall, struct {
		arg1 server.TaskHandler
	}{arg1})
	stub := fake.WithBackgroundTaskHandlerStub
	fakeReturns := fake.withBackgroundTaskHandlerReturns
	fake.recordInvocation("WithBackgroundTaskHandler", []interface{}{arg1})
	fake.withBackgroundTaskHandlerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandlerCallCount() int {
	fake.withBackgroundTaskHandlerMutex.RLock()
	defer fake.withBackgroundTaskHandlerMutex.RUnlock()
	return len(fake.withBackgroundTaskHandlerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandlerCalls(stub func(server.TaskHandler) server.A2AServerBuilder) {
	fake.withBackgroundTaskHandlerMutex.Lock()
	defer fake.withBackgroundTaskHandlerMutex.Unlock()
	fake.WithBackgroundTaskHandlerStub = stub
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandlerArgsForCall(i int) server.TaskHandler {
	fake.withBackgroundTaskHandlerMutex.RLock()
	defer fake.withBackgroundTaskHandlerMutex.RUnlock()
	argsForCall := fake.withBackgroundTaskHandlerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandlerReturns(result1 server.A2AServerBuilder) {
	fake.withBackgroundTaskHandlerMutex.Lock()
	defer fake.withBackgroundTaskHandlerMutex.Unlock()
	fake.WithBackgroundTaskHandlerStub = nil
	fake.withBackgroundTaskHandlerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithBackgroundTaskHandlerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withBackgroundTaskHandlerMutex.Lock()
	defer fake.withBackgroundTaskHandlerMutex.Unlock()
	fake.WithBackgroundTaskHandlerStub = nil
	if fake.withBackgroundTaskHandlerReturnsOnCall == nil {
		fake.withBackgroundTaskHandlerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withBackgroundTaskHandlerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultBackgroundTaskHandler() server.A2AServerBuilder {
	fake.withDefaultBackgroundTaskHandlerMutex.Lock()
	ret, specificReturn := fake.withDefaultBackgroundTaskHandlerReturnsOnCall[len(fake.withDefaultBackgroundTaskHandlerArgsForCall)]
	fake.withDefaultBackgroundTaskHandlerArgsForCall = append(fake.withDefaultBackgroundTaskHandlerArgsForCall, struct {
	}{})
	stub := fake.WithDefaultBackgroundTaskHandlerStub
	fakeReturns := fake.withDefaultBackgroundTaskHandlerReturns
	fake.recordInvocation("WithDefaultBackgroundTaskHandler", []interface{}{})
	fake.withDefaultBackgroundTaskHandlerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithDefaultBackgroundTaskHandlerCallCount() int {
	fake.withDefaultBackgroundTaskHandlerMutex.RLock()
	defer fake.withDefaultBackgroundTaskHandlerMutex.RUnlock()
	return len(fake.withDefaultBackgroundTaskHandlerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithDefaultBackgroundTaskHandlerCalls(stub func() server.A2AServerBuilder) {
	fake.withDefaultBackgroundTaskHandlerMutex.Lock()
	defer fake.withDefaultBackgroundTaskHandlerMutex.Unlock()
	fake.WithDefaultBackgroundTaskHandlerStub = stub
}

func (fake *FakeA2AServerBuilder) WithDefaultBackgroundTaskHandlerReturns(result1 server.A2AServerBuilder) {
	fake.withDefaultBackgroundTaskHandlerMutex.Lock()
	defer fake.withDefaultBackgroundTaskHandlerMutex.Unlock()
	fake.WithDefaultBackgroundTaskHandlerStub = nil
	fake.withDefaultBackgroundTaskHandlerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultBackgroundTaskHandlerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withDefaultBackgroundTaskHandlerMutex.Lock()
	defer fake.withDefaultBackgroundTaskHandlerMutex.Unlock()
	fake.WithDefaultBackgroundTaskHandlerStub = nil
	if fake.withDefaultBackgroundTaskHandlerReturnsOnCall == nil {
		fake.withDefaultBackgroundTaskHandlerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withDefaultBackgroundTaskHandlerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultStreamingTaskHandler() server.A2AServerBuilder {
	fake.withDefaultStreamingTaskHandlerMutex.Lock()
	ret, specificReturn := fake.withDefaultStreamingTaskHandlerReturnsOnCall[len(fake.withDefaultStreamingTaskHandlerArgsForCall)]
	fake.withDefaultStreamingTaskHandlerArgsForCall = append(fake.withDefaultStreamingTaskHandlerArgsForCall, struct {
	}{})
	stub := fake.WithDefaultStreamingTaskHandlerStub
	fakeReturns := fake.withDefaultStreamingTaskHandlerReturns
	fake.recordInvocation("WithDefaultStreamingTaskHandler", []interface{}{})
	fake.withDefaultStreamingTaskHandlerMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithDefaultStreamingTaskHandlerCallCount() int {
	fake.withDefaultStreamingTaskHandlerMutex.RLock()
	defer fake.withDefaultStreamingTaskHandlerMutex.RUnlock()
	return len(fake.withDefaultStreamingTaskHandlerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithDefaultStreamingTaskHandlerCalls(stub func() server.A2AServerBuilder) {
	fake.withDefaultStreamingTaskHandlerMutex.Lock()
	defer fake.withDefaultStreamingTaskHandlerMutex.Unlock()
	fake.WithDefaultStreamingTaskHandlerStub = stub
}

func (fake *FakeA2AServerBuilder) WithDefaultStreamingTaskHandlerReturns(result1 server.A2AServerBuilder) {
	fake.withDefaultStreamingTaskHandlerMutex.Lock()
	defer fake.withDefaultStreamingTaskHandlerMutex.Unlock()
	fake.WithDefaultStreamingTaskHandlerStub = nil
	fake.withDefaultStreamingTaskHandlerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultStreamingTaskHandlerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withDefaultStreamingTaskHandlerMutex.Lock()
	defer fake.withDefaultStreamingTaskHandlerMutex.Unlock()
	fake.WithDefaultStreamingTaskHandlerStub = nil
	if fake.withDefaultStreamingTaskHandlerReturnsOnCall == nil {
		fake.withDefaultStreamingTaskHandlerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withDefaultStreamingTaskHandlerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultTaskHandlers() server.A2AServerBuilder {
	fake.withDefaultTaskHandlersMutex.Lock()
	ret, specificReturn := fake.withDefaultTaskHandlersReturnsOnCall[len(fake.withDefaultTaskHandlersArgsForCall)]
	fake.withDefaultTaskHandlersArgsForCall = append(fake.withDefaultTaskHandlersArgsForCall, struct {
	}{})
	stub := fake.WithDefaultTaskHandlersStub
	fakeReturns := fake.withDefaultTaskHandlersReturns
	fake.recordInvocation("WithDefaultTaskHandlers", []interface{}{})
	fake.withDefaultTaskHandlersMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithDefaultTaskHandlersCallCount() int {
	fake.withDefaultTaskHandlersMutex.RLock()
	defer fake.withDefaultTaskHandlersMutex.RUnlock()
	return len(fake.withDefaultTaskHandlersArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithDefaultTaskHandlersCalls(stub func() server.A2AServerBuilder) {
	fake.withDefaultTaskHandlersMutex.Lock()
	defer fake.withDefaultTaskHandlersMutex.Unlock()
	fake.WithDefaultTaskHandlersStub = stub
}

func (fake *FakeA2AServerBuilder) WithDefaultTaskHandlersReturns(result1 server.A2AServerBuilder) {
	fake.withDefaultTaskHandlersMutex.Lock()
	defer fake.withDefaultTaskHandlersMutex.Unlock()
	fake.WithDefaultTaskHandlersStub = nil
	fake.withDefaultTaskHandlersReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithDefaultTaskHandlersReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withDefaultTaskHandlersMutex.Lock()
	defer fake.withDefaultTaskHandlersMutex.Unlock()
	fake.WithDefaultTaskHandlersStub = nil
	if fake.withDefaultTaskHandlersReturnsOnCall == nil {
		fake.withDefaultTaskHandlersReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withDefaultTaskHandlersReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithLogger(arg1 *zap.Logger) server.A2AServerBuilder {
	fake.withLoggerMutex.Lock()
	ret, specificReturn := fake.withLoggerReturnsOnCall[len(fake.withLoggerArgsForCall)]
	fake.withLoggerArgsForCall = append(fake.withLoggerArgsForCall, struct {
		arg1 *zap.Logger
	}{arg1})
	stub := fake.WithLoggerStub
	fakeReturns := fake.withLoggerReturns
	fake.recordInvocation("WithLogger", []interface{}{arg1})
	fake.withLoggerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithLoggerCallCount() int {
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	return len(fake.withLoggerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithLoggerCalls(stub func(*zap.Logger) server.A2AServerBuilder) {
	fake.withLoggerMutex.Lock()
	defer fake.withLoggerMutex.Unlock()
	fake.WithLoggerStub = stub
}

func (fake *FakeA2AServerBuilder) WithLoggerArgsForCall(i int) *zap.Logger {
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	argsForCall := fake.withLoggerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithLoggerReturns(result1 server.A2AServerBuilder) {
	fake.withLoggerMutex.Lock()
	defer fake.withLoggerMutex.Unlock()
	fake.WithLoggerStub = nil
	fake.withLoggerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithLoggerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withLoggerMutex.Lock()
	defer fake.withLoggerMutex.Unlock()
	fake.WithLoggerStub = nil
	if fake.withLoggerReturnsOnCall == nil {
		fake.withLoggerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withLoggerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandler(arg1 server.StreamableTaskHandler) server.A2AServerBuilder {
	fake.withStreamingTaskHandlerMutex.Lock()
	ret, specificReturn := fake.withStreamingTaskHandlerReturnsOnCall[len(fake.withStreamingTaskHandlerArgsForCall)]
	fake.withStreamingTaskHandlerArgsForCall = append(fake.withStreamingTaskHandlerArgsForCall, struct {
		arg1 server.StreamableTaskHandler
	}{arg1})
	stub := fake.WithStreamingTaskHandlerStub
	fakeReturns := fake.withStreamingTaskHandlerReturns
	fake.recordInvocation("WithStreamingTaskHandler", []interface{}{arg1})
	fake.withStreamingTaskHandlerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandlerCallCount() int {
	fake.withStreamingTaskHandlerMutex.RLock()
	defer fake.withStreamingTaskHandlerMutex.RUnlock()
	return len(fake.withStreamingTaskHandlerArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandlerCalls(stub func(server.StreamableTaskHandler) server.A2AServerBuilder) {
	fake.withStreamingTaskHandlerMutex.Lock()
	defer fake.withStreamingTaskHandlerMutex.Unlock()
	fake.WithStreamingTaskHandlerStub = stub
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandlerArgsForCall(i int) server.StreamableTaskHandler {
	fake.withStreamingTaskHandlerMutex.RLock()
	defer fake.withStreamingTaskHandlerMutex.RUnlock()
	argsForCall := fake.withStreamingTaskHandlerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandlerReturns(result1 server.A2AServerBuilder) {
	fake.withStreamingTaskHandlerMutex.Lock()
	defer fake.withStreamingTaskHandlerMutex.Unlock()
	fake.WithStreamingTaskHandlerStub = nil
	fake.withStreamingTaskHandlerReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithStreamingTaskHandlerReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withStreamingTaskHandlerMutex.Lock()
	defer fake.withStreamingTaskHandlerMutex.Unlock()
	fake.WithStreamingTaskHandlerStub = nil
	if fake.withStreamingTaskHandlerReturnsOnCall == nil {
		fake.withStreamingTaskHandlerReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withStreamingTaskHandlerReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessor(arg1 server.TaskResultProcessor) server.A2AServerBuilder {
	fake.withTaskResultProcessorMutex.Lock()
	ret, specificReturn := fake.withTaskResultProcessorReturnsOnCall[len(fake.withTaskResultProcessorArgsForCall)]
	fake.withTaskResultProcessorArgsForCall = append(fake.withTaskResultProcessorArgsForCall, struct {
		arg1 server.TaskResultProcessor
	}{arg1})
	stub := fake.WithTaskResultProcessorStub
	fakeReturns := fake.withTaskResultProcessorReturns
	fake.recordInvocation("WithTaskResultProcessor", []interface{}{arg1})
	fake.withTaskResultProcessorMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessorCallCount() int {
	fake.withTaskResultProcessorMutex.RLock()
	defer fake.withTaskResultProcessorMutex.RUnlock()
	return len(fake.withTaskResultProcessorArgsForCall)
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessorCalls(stub func(server.TaskResultProcessor) server.A2AServerBuilder) {
	fake.withTaskResultProcessorMutex.Lock()
	defer fake.withTaskResultProcessorMutex.Unlock()
	fake.WithTaskResultProcessorStub = stub
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessorArgsForCall(i int) server.TaskResultProcessor {
	fake.withTaskResultProcessorMutex.RLock()
	defer fake.withTaskResultProcessorMutex.RUnlock()
	argsForCall := fake.withTaskResultProcessorArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessorReturns(result1 server.A2AServerBuilder) {
	fake.withTaskResultProcessorMutex.Lock()
	defer fake.withTaskResultProcessorMutex.Unlock()
	fake.WithTaskResultProcessorStub = nil
	fake.withTaskResultProcessorReturns = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) WithTaskResultProcessorReturnsOnCall(i int, result1 server.A2AServerBuilder) {
	fake.withTaskResultProcessorMutex.Lock()
	defer fake.withTaskResultProcessorMutex.Unlock()
	fake.WithTaskResultProcessorStub = nil
	if fake.withTaskResultProcessorReturnsOnCall == nil {
		fake.withTaskResultProcessorReturnsOnCall = make(map[int]struct {
			result1 server.A2AServerBuilder
		})
	}
	fake.withTaskResultProcessorReturnsOnCall[i] = struct {
		result1 server.A2AServerBuilder
	}{result1}
}

func (fake *FakeA2AServerBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	fake.withAgentMutex.RLock()
	defer fake.withAgentMutex.RUnlock()
	fake.withAgentCardMutex.RLock()
	defer fake.withAgentCardMutex.RUnlock()
	fake.withAgentCardFromFileMutex.RLock()
	defer fake.withAgentCardFromFileMutex.RUnlock()
	fake.withArtifactsServerMutex.RLock()
	defer fake.withArtifactsServerMutex.RUnlock()
	fake.withBackgroundTaskHandlerMutex.RLock()
	defer fake.withBackgroundTaskHandlerMutex.RUnlock()
	fake.withDefaultBackgroundTaskHandlerMutex.RLock()
	defer fake.withDefaultBackgroundTaskHandlerMutex.RUnlock()
	fake.withDefaultStreamingTaskHandlerMutex.RLock()
	defer fake.withDefaultStreamingTaskHandlerMutex.RUnlock()
	fake.withDefaultTaskHandlersMutex.RLock()
	defer fake.withDefaultTaskHandlersMutex.RUnlock()
	fake.withLoggerMutex.RLock()
	defer fake.withLoggerMutex.RUnlock()
	fake.withStreamingTaskHandlerMutex.RLock()
	defer fake.withStreamingTaskHandlerMutex.RUnlock()
	fake.withTaskResultProcessorMutex.RLock()
	defer fake.withTaskResultProcessorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeA2AServerBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.A2AServerBuilder = new(FakeA2AServerBuilder)
