// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/inference-gateway/adk/server"
	redis "github.com/redis/go-redis/v9"
)

type FakeRedisPipeliner struct {
	DelStub        func(context.Context, ...string) *redis.IntCmd
	delMutex       sync.RWMutex
	delArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	delReturns struct {
		result1 *redis.IntCmd
	}
	delReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	ExecStub        func(context.Context) ([]redis.Cmder, error)
	execMutex       sync.RWMutex
	execArgsForCall []struct {
		arg1 context.Context
	}
	execReturns struct {
		result1 []redis.Cmder
		result2 error
	}
	execReturnsOnCall map[int]struct {
		result1 []redis.Cmder
		result2 error
	}
	LPushStub        func(context.Context, string, ...any) *redis.IntCmd
	lPushMutex       sync.RWMutex
	lPushArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}
	lPushReturns struct {
		result1 *redis.IntCmd
	}
	lPushReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	SAddStub        func(context.Context, string, ...any) *redis.IntCmd
	sAddMutex       sync.RWMutex
	sAddArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}
	sAddReturns struct {
		result1 *redis.IntCmd
	}
	sAddReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	SRemStub        func(context.Context, string, ...any) *redis.IntCmd
	sRemMutex       sync.RWMutex
	sRemArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}
	sRemReturns struct {
		result1 *redis.IntCmd
	}
	sRemReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	SetStub        func(context.Context, string, any, time.Duration) *redis.StatusCmd
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 any
		arg4 time.Duration
	}
	setReturns struct {
		result1 *redis.StatusCmd
	}
	setReturnsOnCall map[int]struct {
		result1 *redis.StatusCmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRedisPipeliner) Del(arg1 context.Context, arg2 ...string) *redis.IntCmd {
	fake.delMutex.Lock()
	ret, specificReturn := fake.delReturnsOnCall[len(fake.delArgsForCall)]
	fake.delArgsForCall = append(fake.delArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2})
	stub := fake.DelStub
	fakeReturns := fake.delReturns
	fake.recordInvocation("Del", []interface{}{arg1, arg2})
	fake.delMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisPipeliner) DelCallCount() int {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	return len(fake.delArgsForCall)
}

func (fake *FakeRedisPipeliner) DelCalls(stub func(context.Context, ...string) *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = stub
}

func (fake *FakeRedisPipeliner) DelArgsForCall(i int) (context.Context, []string) {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	argsForCall := fake.delArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisPipeliner) DelReturns(result1 *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	fake.delReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) DelReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	if fake.delReturnsOnCall == nil {
		fake.delReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.delReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) Exec(arg1 context.Context) ([]redis.Cmder, error) {
	fake.execMutex.Lock()
	ret, specificReturn := fake.execReturnsOnCall[len(fake.execArgsForCall)]
	fake.execArgsForCall = append(fake.execArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ExecStub
	fakeReturns := fake.execReturns
	fake.recordInvocation("Exec", []interface{}{arg1})
	fake.execMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeRedisPipeliner) ExecCallCount() int {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	return len(fake.execArgsForCall)
}

func (fake *FakeRedisPipeliner) ExecCalls(stub func(context.Context) ([]redis.Cmder, error)) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = stub
}

func (fake *FakeRedisPipeliner) ExecArgsForCall(i int) context.Context {
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	argsForCall := fake.execArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRedisPipeliner) ExecReturns(result1 []redis.Cmder, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	fake.execReturns = struct {
		result1 []redis.Cmder
		result2 error
	}{result1, result2}
}

func (fake *FakeRedisPipeliner) ExecReturnsOnCall(i int, result1 []redis.Cmder, result2 error) {
	fake.execMutex.Lock()
	defer fake.execMutex.Unlock()
	fake.ExecStub = nil
	if fake.execReturnsOnCall == nil {
		fake.execReturnsOnCall = make(map[int]struct {
			result1 []redis.Cmder
			result2 error
		})
	}
	fake.execReturnsOnCall[i] = struct {
		result1 []redis.Cmder
		result2 error
	}{result1, result2}
}

func (fake *FakeRedisPipeliner) LPush(arg1 context.Context, arg2 string, arg3 ...any) *redis.IntCmd {
	fake.lPushMutex.Lock()
	ret, specificReturn := fake.lPushReturnsOnCall[len(fake.lPushArgsForCall)]
	fake.lPushArgsForCall = append(fake.lPushArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}{arg1, arg2, arg3})
	stub := fake.LPushStub
	fakeReturns := fake.lPushReturns
	fake.recordInvocation("LPush", []interface{}{arg1, arg2, arg3})
	fake.lPushMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisPipeliner) LPushCallCount() int {
	fake.lPushMutex.RLock()
	defer fake.lPushMutex.RUnlock()
	return len(fake.lPushArgsForCall)
}

func (fake *FakeRedisPipeliner) LPushCalls(stub func(context.Context, string, ...any) *redis.IntCmd) {
	fake.lPushMutex.Lock()
	defer fake.lPushMutex.Unlock()
	fake.LPushStub = stub
}

func (fake *FakeRedisPipeliner) LPushArgsForCall(i int) (context.Context, string, []any) {
	fake.lPushMutex.RLock()
	defer fake.lPushMutex.RUnlock()
	argsForCall := fake.lPushArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRedisPipeliner) LPushReturns(result1 *redis.IntCmd) {
	fake.lPushMutex.Lock()
	defer fake.lPushMutex.Unlock()
	fake.LPushStub = nil
	fake.lPushReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) LPushReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.lPushMutex.Lock()
	defer fake.lPushMutex.Unlock()
	fake.LPushStub = nil
	if fake.lPushReturnsOnCall == nil {
		fake.lPushReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.lPushReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) SAdd(arg1 context.Context, arg2 string, arg3 ...any) *redis.IntCmd {
	fake.sAddMutex.Lock()
	ret, specificReturn := fake.sAddReturnsOnCall[len(fake.sAddArgsForCall)]
	fake.sAddArgsForCall = append(fake.sAddArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}{arg1, arg2, arg3})
	stub := fake.SAddStub
	fakeReturns := fake.sAddReturns
	fake.recordInvocation("SAdd", []interface{}{arg1, arg2, arg3})
	fake.sAddMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisPipeliner) SAddCallCount() int {
	fake.sAddMutex.RLock()
	defer fake.sAddMutex.RUnlock()
	return len(fake.sAddArgsForCall)
}

func (fake *FakeRedisPipeliner) SAddCalls(stub func(context.Context, string, ...any) *redis.IntCmd) {
	fake.sAddMutex.Lock()
	defer fake.sAddMutex.Unlock()
	fake.SAddStub = stub
}

func (fake *FakeRedisPipeliner) SAddArgsForCall(i int) (context.Context, string, []any) {
	fake.sAddMutex.RLock()
	defer fake.sAddMutex.RUnlock()
	argsForCall := fake.sAddArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRedisPipeliner) SAddReturns(result1 *redis.IntCmd) {
	fake.sAddMutex.Lock()
	defer fake.sAddMutex.Unlock()
	fake.SAddStub = nil
	fake.sAddReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) SAddReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.sAddMutex.Lock()
	defer fake.sAddMutex.Unlock()
	fake.SAddStub = nil
	if fake.sAddReturnsOnCall == nil {
		fake.sAddReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.sAddReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) SRem(arg1 context.Context, arg2 string, arg3 ...any) *redis.IntCmd {
	fake.sRemMutex.Lock()
	ret, specificReturn := fake.sRemReturnsOnCall[len(fake.sRemArgsForCall)]
	fake.sRemArgsForCall = append(fake.sRemArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []any
	}{arg1, arg2, arg3})
	stub := fake.SRemStub
	fakeReturns := fake.sRemReturns
	fake.recordInvocation("SRem", []interface{}{arg1, arg2, arg3})
	fake.sRemMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisPipeliner) SRemCallCount() int {
	fake.sRemMutex.RLock()
	defer fake.sRemMutex.RUnlock()
	return len(fake.sRemArgsForCall)
}

func (fake *FakeRedisPipeliner) SRemCalls(stub func(context.Context, string, ...any) *redis.IntCmd) {
	fake.sRemMutex.Lock()
	defer fake.sRemMutex.Unlock()
	fake.SRemStub = stub
}

func (fake *FakeRedisPipeliner) SRemArgsForCall(i int) (context.Context, string, []any) {
	fake.sRemMutex.RLock()
	defer fake.sRemMutex.RUnlock()
	argsForCall := fake.sRemArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRedisPipeliner) SRemReturns(result1 *redis.IntCmd) {
	fake.sRemMutex.Lock()
	defer fake.sRemMutex.Unlock()
	fake.SRemStub = nil
	fake.sRemReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) SRemReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.sRemMutex.Lock()
	defer fake.sRemMutex.Unlock()
	fake.SRemStub = nil
	if fake.sRemReturnsOnCall == nil {
		fake.sRemReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.sRemReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) Set(arg1 context.Context, arg2 string, arg3 any, arg4 time.Duration) *redis.StatusCmd {
	fake.setMutex.Lock()
	ret, specificReturn := fake.setReturnsOnCall[len(fake.setArgsForCall)]
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 any
		arg4 time.Duration
	}{arg1, arg2, arg3, arg4})
	stub := fake.SetStub
	fakeReturns := fake.setReturns
	fake.recordInvocation("Set", []interface{}{arg1, arg2, arg3, arg4})
	fake.setMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisPipeliner) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *FakeRedisPipeliner) SetCalls(stub func(context.Context, string, any, time.Duration) *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *FakeRedisPipeliner) SetArgsForCall(i int) (context.Context, string, any, time.Duration) {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRedisPipeliner) SetReturns(result1 *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	fake.setReturns = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) SetReturnsOnCall(i int, result1 *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	if fake.setReturnsOnCall == nil {
		fake.setReturnsOnCall = make(map[int]struct {
			result1 *redis.StatusCmd
		})
	}
	fake.setReturnsOnCall[i] = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisPipeliner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	fake.execMutex.RLock()
	defer fake.execMutex.RUnlock()
	fake.lPushMutex.RLock()
	defer fake.lPushMutex.RUnlock()
	fake.sAddMutex.RLock()
	defer fake.sAddMutex.RUnlock()
	fake.sRemMutex.RLock()
	defer fake.sRemMutex.RUnlock()
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRedisPipeliner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.RedisPipeliner = new(FakeRedisPipeliner)
