// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/inference-gateway/adk/server"
	redis "github.com/redis/go-redis/v9"
)

type FakeRedisClient struct {
	BRPopStub        func(context.Context, time.Duration, ...string) *redis.StringSliceCmd
	bRPopMutex       sync.RWMutex
	bRPopArgsForCall []struct {
		arg1 context.Context
		arg2 time.Duration
		arg3 []string
	}
	bRPopReturns struct {
		result1 *redis.StringSliceCmd
	}
	bRPopReturnsOnCall map[int]struct {
		result1 *redis.StringSliceCmd
	}
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	DelStub        func(context.Context, ...string) *redis.IntCmd
	delMutex       sync.RWMutex
	delArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	delReturns struct {
		result1 *redis.IntCmd
	}
	delReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	ExistsStub        func(context.Context, ...string) *redis.IntCmd
	existsMutex       sync.RWMutex
	existsArgsForCall []struct {
		arg1 context.Context
		arg2 []string
	}
	existsReturns struct {
		result1 *redis.IntCmd
	}
	existsReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	GetStub        func(context.Context, string) *redis.StringCmd
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getReturns struct {
		result1 *redis.StringCmd
	}
	getReturnsOnCall map[int]struct {
		result1 *redis.StringCmd
	}
	KeysStub        func(context.Context, string) *redis.StringSliceCmd
	keysMutex       sync.RWMutex
	keysArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	keysReturns struct {
		result1 *redis.StringSliceCmd
	}
	keysReturnsOnCall map[int]struct {
		result1 *redis.StringSliceCmd
	}
	LLenStub        func(context.Context, string) *redis.IntCmd
	lLenMutex       sync.RWMutex
	lLenArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	lLenReturns struct {
		result1 *redis.IntCmd
	}
	lLenReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	PingStub        func(context.Context) *redis.StatusCmd
	pingMutex       sync.RWMutex
	pingArgsForCall []struct {
		arg1 context.Context
	}
	pingReturns struct {
		result1 *redis.StatusCmd
	}
	pingReturnsOnCall map[int]struct {
		result1 *redis.StatusCmd
	}
	PipelineStub        func() server.RedisPipeliner
	pipelineMutex       sync.RWMutex
	pipelineArgsForCall []struct {
	}
	pipelineReturns struct {
		result1 server.RedisPipeliner
	}
	pipelineReturnsOnCall map[int]struct {
		result1 server.RedisPipeliner
	}
	PublishStub        func(context.Context, string, any) *redis.IntCmd
	publishMutex       sync.RWMutex
	publishArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 any
	}
	publishReturns struct {
		result1 *redis.IntCmd
	}
	publishReturnsOnCall map[int]struct {
		result1 *redis.IntCmd
	}
	SMembersStub        func(context.Context, string) *redis.StringSliceCmd
	sMembersMutex       sync.RWMutex
	sMembersArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	sMembersReturns struct {
		result1 *redis.StringSliceCmd
	}
	sMembersReturnsOnCall map[int]struct {
		result1 *redis.StringSliceCmd
	}
	SetStub        func(context.Context, string, any, time.Duration) *redis.StatusCmd
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 any
		arg4 time.Duration
	}
	setReturns struct {
		result1 *redis.StatusCmd
	}
	setReturnsOnCall map[int]struct {
		result1 *redis.StatusCmd
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRedisClient) BRPop(arg1 context.Context, arg2 time.Duration, arg3 ...string) *redis.StringSliceCmd {
	fake.bRPopMutex.Lock()
	ret, specificReturn := fake.bRPopReturnsOnCall[len(fake.bRPopArgsForCall)]
	fake.bRPopArgsForCall = append(fake.bRPopArgsForCall, struct {
		arg1 context.Context
		arg2 time.Duration
		arg3 []string
	}{arg1, arg2, arg3})
	stub := fake.BRPopStub
	fakeReturns := fake.bRPopReturns
	fake.recordInvocation("BRPop", []interface{}{arg1, arg2, arg3})
	fake.bRPopMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) BRPopCallCount() int {
	fake.bRPopMutex.RLock()
	defer fake.bRPopMutex.RUnlock()
	return len(fake.bRPopArgsForCall)
}

func (fake *FakeRedisClient) BRPopCalls(stub func(context.Context, time.Duration, ...string) *redis.StringSliceCmd) {
	fake.bRPopMutex.Lock()
	defer fake.bRPopMutex.Unlock()
	fake.BRPopStub = stub
}

func (fake *FakeRedisClient) BRPopArgsForCall(i int) (context.Context, time.Duration, []string) {
	fake.bRPopMutex.RLock()
	defer fake.bRPopMutex.RUnlock()
	argsForCall := fake.bRPopArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRedisClient) BRPopReturns(result1 *redis.StringSliceCmd) {
	fake.bRPopMutex.Lock()
	defer fake.bRPopMutex.Unlock()
	fake.BRPopStub = nil
	fake.bRPopReturns = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) BRPopReturnsOnCall(i int, result1 *redis.StringSliceCmd) {
	fake.bRPopMutex.Lock()
	defer fake.bRPopMutex.Unlock()
	fake.BRPopStub = nil
	if fake.bRPopReturnsOnCall == nil {
		fake.bRPopReturnsOnCall = make(map[int]struct {
			result1 *redis.StringSliceCmd
		})
	}
	fake.bRPopReturnsOnCall[i] = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fakeReturns := fake.closeReturns
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeRedisClient) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeRedisClient) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeRedisClient) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeRedisClient) Del(arg1 context.Context, arg2 ...string) *redis.IntCmd {
	fake.delMutex.Lock()
	ret, specificReturn := fake.delReturnsOnCall[len(fake.delArgsForCall)]
	fake.delArgsForCall = append(fake.delArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2})
	stub := fake.DelStub
	fakeReturns := fake.delReturns
	fake.recordInvocation("Del", []interface{}{arg1, arg2})
	fake.delMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) DelCallCount() int {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	return len(fake.delArgsForCall)
}

func (fake *FakeRedisClient) DelCalls(stub func(context.Context, ...string) *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = stub
}

func (fake *FakeRedisClient) DelArgsForCall(i int) (context.Context, []string) {
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	argsForCall := fake.delArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) DelReturns(result1 *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	fake.delReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) DelReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.delMutex.Lock()
	defer fake.delMutex.Unlock()
	fake.DelStub = nil
	if fake.delReturnsOnCall == nil {
		fake.delReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.delReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) Exists(arg1 context.Context, arg2 ...string) *redis.IntCmd {
	fake.existsMutex.Lock()
	ret, specificReturn := fake.existsReturnsOnCall[len(fake.existsArgsForCall)]
	fake.existsArgsForCall = append(fake.existsArgsForCall, struct {
		arg1 context.Context
		arg2 []string
	}{arg1, arg2})
	stub := fake.ExistsStub
	fakeReturns := fake.existsReturns
	fake.recordInvocation("Exists", []interface{}{arg1, arg2})
	fake.existsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) ExistsCallCount() int {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	return len(fake.existsArgsForCall)
}

func (fake *FakeRedisClient) ExistsCalls(stub func(context.Context, ...string) *redis.IntCmd) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = stub
}

func (fake *FakeRedisClient) ExistsArgsForCall(i int) (context.Context, []string) {
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	argsForCall := fake.existsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) ExistsReturns(result1 *redis.IntCmd) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	fake.existsReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) ExistsReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.existsMutex.Lock()
	defer fake.existsMutex.Unlock()
	fake.ExistsStub = nil
	if fake.existsReturnsOnCall == nil {
		fake.existsReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.existsReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) Get(arg1 context.Context, arg2 string) *redis.StringCmd {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeRedisClient) GetCalls(stub func(context.Context, string) *redis.StringCmd) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeRedisClient) GetArgsForCall(i int) (context.Context, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) GetReturns(result1 *redis.StringCmd) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *redis.StringCmd
	}{result1}
}

func (fake *FakeRedisClient) GetReturnsOnCall(i int, result1 *redis.StringCmd) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *redis.StringCmd
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *redis.StringCmd
	}{result1}
}

func (fake *FakeRedisClient) Keys(arg1 context.Context, arg2 string) *redis.StringSliceCmd {
	fake.keysMutex.Lock()
	ret, specificReturn := fake.keysReturnsOnCall[len(fake.keysArgsForCall)]
	fake.keysArgsForCall = append(fake.keysArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.KeysStub
	fakeReturns := fake.keysReturns
	fake.recordInvocation("Keys", []interface{}{arg1, arg2})
	fake.keysMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) KeysCallCount() int {
	fake.keysMutex.RLock()
	defer fake.keysMutex.RUnlock()
	return len(fake.keysArgsForCall)
}

func (fake *FakeRedisClient) KeysCalls(stub func(context.Context, string) *redis.StringSliceCmd) {
	fake.keysMutex.Lock()
	defer fake.keysMutex.Unlock()
	fake.KeysStub = stub
}

func (fake *FakeRedisClient) KeysArgsForCall(i int) (context.Context, string) {
	fake.keysMutex.RLock()
	defer fake.keysMutex.RUnlock()
	argsForCall := fake.keysArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) KeysReturns(result1 *redis.StringSliceCmd) {
	fake.keysMutex.Lock()
	defer fake.keysMutex.Unlock()
	fake.KeysStub = nil
	fake.keysReturns = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) KeysReturnsOnCall(i int, result1 *redis.StringSliceCmd) {
	fake.keysMutex.Lock()
	defer fake.keysMutex.Unlock()
	fake.KeysStub = nil
	if fake.keysReturnsOnCall == nil {
		fake.keysReturnsOnCall = make(map[int]struct {
			result1 *redis.StringSliceCmd
		})
	}
	fake.keysReturnsOnCall[i] = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) LLen(arg1 context.Context, arg2 string) *redis.IntCmd {
	fake.lLenMutex.Lock()
	ret, specificReturn := fake.lLenReturnsOnCall[len(fake.lLenArgsForCall)]
	fake.lLenArgsForCall = append(fake.lLenArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.LLenStub
	fakeReturns := fake.lLenReturns
	fake.recordInvocation("LLen", []interface{}{arg1, arg2})
	fake.lLenMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) LLenCallCount() int {
	fake.lLenMutex.RLock()
	defer fake.lLenMutex.RUnlock()
	return len(fake.lLenArgsForCall)
}

func (fake *FakeRedisClient) LLenCalls(stub func(context.Context, string) *redis.IntCmd) {
	fake.lLenMutex.Lock()
	defer fake.lLenMutex.Unlock()
	fake.LLenStub = stub
}

func (fake *FakeRedisClient) LLenArgsForCall(i int) (context.Context, string) {
	fake.lLenMutex.RLock()
	defer fake.lLenMutex.RUnlock()
	argsForCall := fake.lLenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) LLenReturns(result1 *redis.IntCmd) {
	fake.lLenMutex.Lock()
	defer fake.lLenMutex.Unlock()
	fake.LLenStub = nil
	fake.lLenReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) LLenReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.lLenMutex.Lock()
	defer fake.lLenMutex.Unlock()
	fake.LLenStub = nil
	if fake.lLenReturnsOnCall == nil {
		fake.lLenReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.lLenReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) Ping(arg1 context.Context) *redis.StatusCmd {
	fake.pingMutex.Lock()
	ret, specificReturn := fake.pingReturnsOnCall[len(fake.pingArgsForCall)]
	fake.pingArgsForCall = append(fake.pingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PingStub
	fakeReturns := fake.pingReturns
	fake.recordInvocation("Ping", []interface{}{arg1})
	fake.pingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) PingCallCount() int {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	return len(fake.pingArgsForCall)
}

func (fake *FakeRedisClient) PingCalls(stub func(context.Context) *redis.StatusCmd) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = stub
}

func (fake *FakeRedisClient) PingArgsForCall(i int) context.Context {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	argsForCall := fake.pingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeRedisClient) PingReturns(result1 *redis.StatusCmd) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	fake.pingReturns = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisClient) PingReturnsOnCall(i int, result1 *redis.StatusCmd) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	if fake.pingReturnsOnCall == nil {
		fake.pingReturnsOnCall = make(map[int]struct {
			result1 *redis.StatusCmd
		})
	}
	fake.pingReturnsOnCall[i] = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisClient) Pipeline() server.RedisPipeliner {
	fake.pipelineMutex.Lock()
	ret, specificReturn := fake.pipelineReturnsOnCall[len(fake.pipelineArgsForCall)]
	fake.pipelineArgsForCall = append(fake.pipelineArgsForCall, struct {
	}{})
	stub := fake.PipelineStub
	fakeReturns := fake.pipelineReturns
	fake.recordInvocation("Pipeline", []interface{}{})
	fake.pipelineMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) PipelineCallCount() int {
	fake.pipelineMutex.RLock()
	defer fake.pipelineMutex.RUnlock()
	return len(fake.pipelineArgsForCall)
}

func (fake *FakeRedisClient) PipelineCalls(stub func() server.RedisPipeliner) {
	fake.pipelineMutex.Lock()
	defer fake.pipelineMutex.Unlock()
	fake.PipelineStub = stub
}

func (fake *FakeRedisClient) PipelineReturns(result1 server.RedisPipeliner) {
	fake.pipelineMutex.Lock()
	defer fake.pipelineMutex.Unlock()
	fake.PipelineStub = nil
	fake.pipelineReturns = struct {
		result1 server.RedisPipeliner
	}{result1}
}

func (fake *FakeRedisClient) PipelineReturnsOnCall(i int, result1 server.RedisPipeliner) {
	fake.pipelineMutex.Lock()
	defer fake.pipelineMutex.Unlock()
	fake.PipelineStub = nil
	if fake.pipelineReturnsOnCall == nil {
		fake.pipelineReturnsOnCall = make(map[int]struct {
			result1 server.RedisPipeliner
		})
	}
	fake.pipelineReturnsOnCall[i] = struct {
		result1 server.RedisPipeliner
	}{result1}
}

func (fake *FakeRedisClient) Publish(arg1 context.Context, arg2 string, arg3 any) *redis.IntCmd {
	fake.publishMutex.Lock()
	ret, specificReturn := fake.publishReturnsOnCall[len(fake.publishArgsForCall)]
	fake.publishArgsForCall = append(fake.publishArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 any
	}{arg1, arg2, arg3})
	stub := fake.PublishStub
	fakeReturns := fake.publishReturns
	fake.recordInvocation("Publish", []interface{}{arg1, arg2, arg3})
	fake.publishMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) PublishCallCount() int {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return len(fake.publishArgsForCall)
}

func (fake *FakeRedisClient) PublishCalls(stub func(context.Context, string, any) *redis.IntCmd) {
	fake.publishMutex.Lock()
	defer fake.publishMutex.Unlock()
	fake.PublishStub = stub
}

func (fake *FakeRedisClient) PublishArgsForCall(i int) (context.Context, string, any) {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	argsForCall := fake.publishArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeRedisClient) PublishReturns(result1 *redis.IntCmd) {
	fake.publishMutex.Lock()
	defer fake.publishMutex.Unlock()
	fake.PublishStub = nil
	fake.publishReturns = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) PublishReturnsOnCall(i int, result1 *redis.IntCmd) {
	fake.publishMutex.Lock()
	defer fake.publishMutex.Unlock()
	fake.PublishStub = nil
	if fake.publishReturnsOnCall == nil {
		fake.publishReturnsOnCall = make(map[int]struct {
			result1 *redis.IntCmd
		})
	}
	fake.publishReturnsOnCall[i] = struct {
		result1 *redis.IntCmd
	}{result1}
}

func (fake *FakeRedisClient) SMembers(arg1 context.Context, arg2 string) *redis.StringSliceCmd {
	fake.sMembersMutex.Lock()
	ret, specificReturn := fake.sMembersReturnsOnCall[len(fake.sMembersArgsForCall)]
	fake.sMembersArgsForCall = append(fake.sMembersArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SMembersStub
	fakeReturns := fake.sMembersReturns
	fake.recordInvocation("SMembers", []interface{}{arg1, arg2})
	fake.sMembersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) SMembersCallCount() int {
	fake.sMembersMutex.RLock()
	defer fake.sMembersMutex.RUnlock()
	return len(fake.sMembersArgsForCall)
}

func (fake *FakeRedisClient) SMembersCalls(stub func(context.Context, string) *redis.StringSliceCmd) {
	fake.sMembersMutex.Lock()
	defer fake.sMembersMutex.Unlock()
	fake.SMembersStub = stub
}

func (fake *FakeRedisClient) SMembersArgsForCall(i int) (context.Context, string) {
	fake.sMembersMutex.RLock()
	defer fake.sMembersMutex.RUnlock()
	argsForCall := fake.sMembersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeRedisClient) SMembersReturns(result1 *redis.StringSliceCmd) {
	fake.sMembersMutex.Lock()
	defer fake.sMembersMutex.Unlock()
	fake.SMembersStub = nil
	fake.sMembersReturns = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) SMembersReturnsOnCall(i int, result1 *redis.StringSliceCmd) {
	fake.sMembersMutex.Lock()
	defer fake.sMembersMutex.Unlock()
	fake.SMembersStub = nil
	if fake.sMembersReturnsOnCall == nil {
		fake.sMembersReturnsOnCall = make(map[int]struct {
			result1 *redis.StringSliceCmd
		})
	}
	fake.sMembersReturnsOnCall[i] = struct {
		result1 *redis.StringSliceCmd
	}{result1}
}

func (fake *FakeRedisClient) Set(arg1 context.Context, arg2 string, arg3 any, arg4 time.Duration) *redis.StatusCmd {
	fake.setMutex.Lock()
	ret, specificReturn := fake.setReturnsOnCall[len(fake.setArgsForCall)]
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 any
		arg4 time.Duration
	}{arg1, arg2, arg3, arg4})
	stub := fake.SetStub
	fakeReturns := fake.setReturns
	fake.recordInvocation("Set", []interface{}{arg1, arg2, arg3, arg4})
	fake.setMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeRedisClient) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *FakeRedisClient) SetCalls(stub func(context.Context, string, any, time.Duration) *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *FakeRedisClient) SetArgsForCall(i int) (context.Context, string, any, time.Duration) {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeRedisClient) SetReturns(result1 *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	fake.setReturns = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisClient) SetReturnsOnCall(i int, result1 *redis.StatusCmd) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = nil
	if fake.setReturnsOnCall == nil {
		fake.setReturnsOnCall = make(map[int]struct {
			result1 *redis.StatusCmd
		})
	}
	fake.setReturnsOnCall[i] = struct {
		result1 *redis.StatusCmd
	}{result1}
}

func (fake *FakeRedisClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.bRPopMutex.RLock()
	defer fake.bRPopMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.delMutex.RLock()
	defer fake.delMutex.RUnlock()
	fake.existsMutex.RLock()
	defer fake.existsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.keysMutex.RLock()
	defer fake.keysMutex.RUnlock()
	fake.lLenMutex.RLock()
	defer fake.lLenMutex.RUnlock()
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	fake.pipelineMutex.RLock()
	defer fake.pipelineMutex.RUnlock()
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	fake.sMembersMutex.RLock()
	defer fake.sMembersMutex.RUnlock()
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRedisClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.RedisClient = new(FakeRedisClient)
