// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/inference-gateway/adk/server"
	"github.com/inference-gateway/sdk"
)

type FakeLLMClient struct {
	CreateChatCompletionStub        func(context.Context, []sdk.Message, ...sdk.ChatCompletionTool) (*sdk.CreateChatCompletionResponse, error)
	createChatCompletionMutex       sync.RWMutex
	createChatCompletionArgsForCall []struct {
		arg1 context.Context
		arg2 []sdk.Message
		arg3 []sdk.ChatCompletionTool
	}
	createChatCompletionReturns struct {
		result1 *sdk.CreateChatCompletionResponse
		result2 error
	}
	createChatCompletionReturnsOnCall map[int]struct {
		result1 *sdk.CreateChatCompletionResponse
		result2 error
	}
	CreateStreamingChatCompletionStub        func(context.Context, []sdk.Message, ...sdk.ChatCompletionTool) (<-chan *sdk.CreateChatCompletionStreamResponse, <-chan error)
	createStreamingChatCompletionMutex       sync.RWMutex
	createStreamingChatCompletionArgsForCall []struct {
		arg1 context.Context
		arg2 []sdk.Message
		arg3 []sdk.ChatCompletionTool
	}
	createStreamingChatCompletionReturns struct {
		result1 <-chan *sdk.CreateChatCompletionStreamResponse
		result2 <-chan error
	}
	createStreamingChatCompletionReturnsOnCall map[int]struct {
		result1 <-chan *sdk.CreateChatCompletionStreamResponse
		result2 <-chan error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLLMClient) CreateChatCompletion(arg1 context.Context, arg2 []sdk.Message, arg3 ...sdk.ChatCompletionTool) (*sdk.CreateChatCompletionResponse, error) {
	var arg2Copy []sdk.Message
	if arg2 != nil {
		arg2Copy = make([]sdk.Message, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.createChatCompletionMutex.Lock()
	ret, specificReturn := fake.createChatCompletionReturnsOnCall[len(fake.createChatCompletionArgsForCall)]
	fake.createChatCompletionArgsForCall = append(fake.createChatCompletionArgsForCall, struct {
		arg1 context.Context
		arg2 []sdk.Message
		arg3 []sdk.ChatCompletionTool
	}{arg1, arg2Copy, arg3})
	stub := fake.CreateChatCompletionStub
	fakeReturns := fake.createChatCompletionReturns
	fake.recordInvocation("CreateChatCompletion", []interface{}{arg1, arg2Copy, arg3})
	fake.createChatCompletionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLLMClient) CreateChatCompletionCallCount() int {
	fake.createChatCompletionMutex.RLock()
	defer fake.createChatCompletionMutex.RUnlock()
	return len(fake.createChatCompletionArgsForCall)
}

func (fake *FakeLLMClient) CreateChatCompletionCalls(stub func(context.Context, []sdk.Message, ...sdk.ChatCompletionTool) (*sdk.CreateChatCompletionResponse, error)) {
	fake.createChatCompletionMutex.Lock()
	defer fake.createChatCompletionMutex.Unlock()
	fake.CreateChatCompletionStub = stub
}

func (fake *FakeLLMClient) CreateChatCompletionArgsForCall(i int) (context.Context, []sdk.Message, []sdk.ChatCompletionTool) {
	fake.createChatCompletionMutex.RLock()
	defer fake.createChatCompletionMutex.RUnlock()
	argsForCall := fake.createChatCompletionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeLLMClient) CreateChatCompletionReturns(result1 *sdk.CreateChatCompletionResponse, result2 error) {
	fake.createChatCompletionMutex.Lock()
	defer fake.createChatCompletionMutex.Unlock()
	fake.CreateChatCompletionStub = nil
	fake.createChatCompletionReturns = struct {
		result1 *sdk.CreateChatCompletionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeLLMClient) CreateChatCompletionReturnsOnCall(i int, result1 *sdk.CreateChatCompletionResponse, result2 error) {
	fake.createChatCompletionMutex.Lock()
	defer fake.createChatCompletionMutex.Unlock()
	fake.CreateChatCompletionStub = nil
	if fake.createChatCompletionReturnsOnCall == nil {
		fake.createChatCompletionReturnsOnCall = make(map[int]struct {
			result1 *sdk.CreateChatCompletionResponse
			result2 error
		})
	}
	fake.createChatCompletionReturnsOnCall[i] = struct {
		result1 *sdk.CreateChatCompletionResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeLLMClient) CreateStreamingChatCompletion(arg1 context.Context, arg2 []sdk.Message, arg3 ...sdk.ChatCompletionTool) (<-chan *sdk.CreateChatCompletionStreamResponse, <-chan error) {
	var arg2Copy []sdk.Message
	if arg2 != nil {
		arg2Copy = make([]sdk.Message, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.createStreamingChatCompletionMutex.Lock()
	ret, specificReturn := fake.createStreamingChatCompletionReturnsOnCall[len(fake.createStreamingChatCompletionArgsForCall)]
	fake.createStreamingChatCompletionArgsForCall = append(fake.createStreamingChatCompletionArgsForCall, struct {
		arg1 context.Context
		arg2 []sdk.Message
		arg3 []sdk.ChatCompletionTool
	}{arg1, arg2Copy, arg3})
	stub := fake.CreateStreamingChatCompletionStub
	fakeReturns := fake.createStreamingChatCompletionReturns
	fake.recordInvocation("CreateStreamingChatCompletion", []interface{}{arg1, arg2Copy, arg3})
	fake.createStreamingChatCompletionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLLMClient) CreateStreamingChatCompletionCallCount() int {
	fake.createStreamingChatCompletionMutex.RLock()
	defer fake.createStreamingChatCompletionMutex.RUnlock()
	return len(fake.createStreamingChatCompletionArgsForCall)
}

func (fake *FakeLLMClient) CreateStreamingChatCompletionCalls(stub func(context.Context, []sdk.Message, ...sdk.ChatCompletionTool) (<-chan *sdk.CreateChatCompletionStreamResponse, <-chan error)) {
	fake.createStreamingChatCompletionMutex.Lock()
	defer fake.createStreamingChatCompletionMutex.Unlock()
	fake.CreateStreamingChatCompletionStub = stub
}

func (fake *FakeLLMClient) CreateStreamingChatCompletionArgsForCall(i int) (context.Context, []sdk.Message, []sdk.ChatCompletionTool) {
	fake.createStreamingChatCompletionMutex.RLock()
	defer fake.createStreamingChatCompletionMutex.RUnlock()
	argsForCall := fake.createStreamingChatCompletionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeLLMClient) CreateStreamingChatCompletionReturns(result1 <-chan *sdk.CreateChatCompletionStreamResponse, result2 <-chan error) {
	fake.createStreamingChatCompletionMutex.Lock()
	defer fake.createStreamingChatCompletionMutex.Unlock()
	fake.CreateStreamingChatCompletionStub = nil
	fake.createStreamingChatCompletionReturns = struct {
		result1 <-chan *sdk.CreateChatCompletionStreamResponse
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeLLMClient) CreateStreamingChatCompletionReturnsOnCall(i int, result1 <-chan *sdk.CreateChatCompletionStreamResponse, result2 <-chan error) {
	fake.createStreamingChatCompletionMutex.Lock()
	defer fake.createStreamingChatCompletionMutex.Unlock()
	fake.CreateStreamingChatCompletionStub = nil
	if fake.createStreamingChatCompletionReturnsOnCall == nil {
		fake.createStreamingChatCompletionReturnsOnCall = make(map[int]struct {
			result1 <-chan *sdk.CreateChatCompletionStreamResponse
			result2 <-chan error
		})
	}
	fake.createStreamingChatCompletionReturnsOnCall[i] = struct {
		result1 <-chan *sdk.CreateChatCompletionStreamResponse
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeLLMClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createChatCompletionMutex.RLock()
	defer fake.createChatCompletionMutex.RUnlock()
	fake.createStreamingChatCompletionMutex.RLock()
	defer fake.createStreamingChatCompletionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLLMClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ server.LLMClient = new(FakeLLMClient)
