---
services:
  server:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.server
      args:
        AGENT_NAME: streaming-agent
        AGENT_DESCRIPTION: An agent that streams responses in real-time
        AGENT_VERSION: 0.1.0
        EXAMPLE_PATH: examples/streaming
        COMPONENT: server
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: development
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_CAPABILITIES_STREAMING: true
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - http://localhost:8080/health
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - a2a-network

  client:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.client
      args:
        EXAMPLE_PATH: examples/streaming
        COMPONENT: client
    depends_on:
      server:
        condition: service_healthy
    environment:
      SERVER_URL: http://server:8080
    networks:
      - a2a-network

  a2a-debugger:
    image: ghcr.io/inference-gateway/a2a-debugger:latest
    pull_policy: always
    entrypoint:
      - /a2a
      - --server-url
      - http://server:8080
    networks:
      - a2a-network
    profiles:
      - manual

networks:
  a2a-network:
    driver: bridge
