---
services:
  server:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.server
      args:
        AGENT_NAME: streaming-agent
        AGENT_DESCRIPTION: An agent that streams responses in real-time
        AGENT_VERSION: 0.1.0
        LD_FLAGS: "-w -s -X 'main.AgentName=${AGENT_NAME}' -X 'main.AgentDescription=${AGENT_DESCRIPTION}' -X 'main.AgentVersion=${AGENT_VERSION}'"
        EXAMPLE_PATH: examples/streaming
        COMPONENT: server
    ports:
      - "8080:8080"
    environment:
      ENVIRONMENT: development
      A2A_SERVER_PORT: 8080
      A2A_DEBUG: true
      A2A_CAPABILITIES_STREAMING: true
      A2A_CAPABILITIES_PUSH_NOTIFICATIONS: false
    networks:
      - a2a-network

  client:
    build:
      context: ../..
      dockerfile: examples/Dockerfile.client
      args:
        LD_FLAGS: "-w -s"
        EXAMPLE_PATH: examples/streaming
        COMPONENT: client
    depends_on:
      - server
    environment:
      SERVER_URL: http://server:8080
    command: sh -c "sleep 5 && /app/client"
    networks:
      - a2a-network

networks:
  a2a-network:
    driver: bridge
